include:
  - ../../networks/proxy_private.yaml
  - ../../volumes/smb-multimedia.yaml

services:
  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:2.24.0@sha256:4e3ea23c551706c6d7934e2b48e9c4015a60ef5d70f965d3f4e5b68d59ef6c95
    container_name: audiobookshelf
    restart: unless-stopped
    user: 1000:1000
    networks:
      - proxy_private
    volumes:
      - smb.multimedia:/multimedia
      #- ./audiobooks:/audiobooks
      #- ./podcasts:/podcasts
      - /srv/application_data/audiobookshelf/app/metadata:/metadata
      - /srv/application_data/audiobookshelf/app/config:/config
    labels:
      diun.enable: "true"
      traefik.enable: "true"
      # Frontend => Router
      traefik.http.routers.audiobookshelf.entrypoints: websecure
      traefik.http.routers.audiobookshelf.rule: Host(`${AUDIOBOOKSHELF_URL_PREFIX:-audiobookshelf.}${NETWORK_DOMAIN}`)
      traefik.http.routers.audiobookshelf.tls.certresolver: dns-cloudflare
      # Frontend => Services
      traefik.http.routers.audiobookshelf.service: audiobookshelf
      traefik.http.services.audiobookshelf.loadbalancer.server.port: 80
