include:
  - ../../networks/proxy_private.yaml
  - ../../volumes/smb-multimedia.yaml

services:
  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:2.26.3@sha256:fe2ec344b4881ee0fad5c1605e7069c993c218c103e8a57e467e381ee9eebcfb
    container_name: audiobookshelf
    restart: unless-stopped
    user: 1000:1000
    networks:
      - proxy_private
    volumes:
      - smb.multimedia:/multimedia
      #- ./audiobooks:/audiobooks
      #- ./podcasts:/podcasts
      - /srv/application_data/audiobookshelf/app/metadata:/metadata
      - /srv/application_data/audiobookshelf/app/config:/config
    labels:
      diun.enable: "true"
      traefik.enable: "true"
      # Frontend => Router
      traefik.http.routers.audiobookshelf.entrypoints: websecure
      traefik.http.routers.audiobookshelf.rule: Host(`${AUDIOBOOKSHELF_URL_PREFIX:-audiobookshelf.}${NETWORK_DOMAIN}`)
      traefik.http.routers.audiobookshelf.tls.certresolver: dns-cloudflare
      # Frontend => Services
      traefik.http.routers.audiobookshelf.service: audiobookshelf
      traefik.http.services.audiobookshelf.loadbalancer.server.port: 80
