include:
  - ../../networks/proxy_private.yaml
  - ../../volumes/smb-multimedia.yaml

services:
  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:2.26.3
    container_name: audiobookshelf
    restart: unless-stopped
    user: 1000:1000
    networks:
      - proxy_private
    volumes:
      - smb.multimedia:/multimedia
      #- ./audiobooks:/audiobooks
      #- ./podcasts:/podcasts
      - /srv/application_data/audiobookshelf/app/metadata:/metadata
      - /srv/application_data/audiobookshelf/app/config:/config
    labels:
      # What's Up Docker
      wud.watch: true
      wud.watch.digest: false
      wud.display.icon: sh:audiobookshelf
      wud.tag.include: ^\d+\.\d+\.\d+$$
      # Traefik
      traefik.enable: "true"
      # Traefik, Router
      traefik.http.routers.audiobookshelf.entrypoints: websecure
      traefik.http.routers.audiobookshelf.rule: Host(`${AUDIOBOOKSHELF_URL_PREFIX:-audiobookshelf.}${NETWORK_DOMAIN}`)
      traefik.http.routers.audiobookshelf.tls.certresolver: dns-cloudflare
      # Traefik, Services
      traefik.http.routers.audiobookshelf.service: audiobookshelf
      traefik.http.services.audiobookshelf.loadbalancer.server.port: 80
