include:
  - ../../networks/proxy_private.yaml

services:
  requestrr:
    image: thomst08/requestrr:v2.1.8
    container_name: requestrr
    restart: unless-stopped
    networks:
      - proxy_private
    volumes:
      - /srv/application_data/requestrr/app/config:/root/config
    labels:
      # Glance
      glance.name: Requestrr
      glance.icon: sh:requestrr
      glance.url: https://${REQUESTRR_URL_PREFIX:-requestrr.}${NETWORK_DOMAIN}
      glance.description: Discord-based media library requests
      glance.category: media-management
      # What's Up Docker
      wud.watch: true
      wud.watch.digest: false
      wud.link.template: https://github.com/thomst08/requestrr/releases/tag/V$${major}.$${minor}.$${patch}
      wud.display.icon: sh:requestrr
      wud.tag.include: ^v\d+\.\d+\.\d+$$
      # Traefik
      traefik.enable: "true"
      # Traefik, Router
      traefik.http.routers.requestrr.entrypoints: websecure
      traefik.http.routers.requestrr.rule: Host(`${REQUESTRR_URL_PREFIX:-requestrr.}${NETWORK_DOMAIN}`)
      traefik.http.routers.requestrr.tls.certresolver: dns-cloudflare
      # Traefik, Services
      traefik.http.routers.requestrr.service: requestrr
      traefik.http.services.requestrr.loadbalancer.server.port: 4545
