include:
  - ../../networks/proxy_private.yaml

services:
  requestrr:
    image: thomst08/requestrr:2.1.8
    container_name: requestrr
    restart: unless-stopped
    networks:
      - proxy_private
    volumes:
      - /srv/application_data/requestrr/app/config:/root/config
    labels:
      # What's Up Docker
      wud.watch: true
      wud.watch.digest: false
      wud.display.icon: sh:requestrr
      wud.tag.include: ^\d+\.\d+\.\d+$$
      # Traefik
      traefik.enable: "true"
      # Traefik, Router
      traefik.http.routers.requestrr.entrypoints: websecure
      traefik.http.routers.requestrr.rule: Host(`${REQUESTRR_URL_PREFIX:-requestrr.}${NETWORK_DOMAIN}`)
      traefik.http.routers.requestrr.tls.certresolver: dns-cloudflare
      # Traefik, Services
      traefik.http.routers.requestrr.service: requestrr
      traefik.http.services.requestrr.loadbalancer.server.port: 4545
