[[stack]]
name = "requestrr"
tags = ["media-management"]
[stack.config]
server = "hyperion"
links = [
  "https://requestrr.jekotia.net",
  "https://github.com/thomst08/requestrr",
  "https://hub.docker.com/r/thomst08/requestrr"
]
git_account = "jekotia"
repo = "jekotia/saturn"
branch = "master"
webhook_enabled = false
run_directory = "docker/stacks/requestrr/"
file_paths = [
  "compose.yaml",
  "../../networks/proxy_private.yaml"
]
environment = """
# REQUESTRR_URL_PREFIX=
NETWORK_DOMAIN=[[NETWORK_DOMAIN]]
"""