include:
  - ../../networks/proxy_private.yaml
services:
  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    restart: unless-stopped
    environment:
      PMA_ARBITRARY: "1"
      PMA_ABSOLUTE_URI: https://${PHPMYADMIN_URL_PREFIX:-phpmyadmin.}${NETWORK_DOMAIN}
      UPLOAD_LIMIT: 100M
    networks:
      - proxy_private
      - database
    labels:
      traefik.enable: "true"
      # Frontend => Router
      traefik.http.routers.phpmyadmin.entrypoints: websecure
      traefik.http.routers.phpmyadmin.rule: Host(`${PHPMYADMIN_URL_PREFIX:-phpmyadmin.}${NETWORK_DOMAIN}`)
      traefik.http.routers.phpmyadmin.tls.certresolver: dns-cloudflare
      # Frontend => Services
      traefik.http.routers.phpmyadmin.service: phpmyadmin
      traefik.http.services.phpmyadmin.loadbalancer.server.port: 80

networks:
  database:
    name: ${PHPMYADMIN_DATABASE_NETWORK}
    external: true
