include:
  - ../../networks/proxy_private.yaml
services:
  phpmyadmin.db:
    image: mariadb:10.3
    container_name: phpmyadmin.db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MARIADB_USER: jekotia
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
    networks:
      - mysql-workbench

  phpmyadmin.app:
    image: phpmyadmin
    container_name: phpmyadmin.app
    restart: unless-stopped
    environment:
      #PMA_ARBITRARY: "1"
      PMA_HOST: phpmyadmin.db
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      UPLOAD_LIMIT: 100M
    networks:
      - proxy_private
      - mysql-workbench
    labels:
      traefik.enable: "true"
      # Frontend => Router
      traefik.http.routers.phpmyadmin.entrypoints: websecure
      traefik.http.routers.phpmyadmin.rule: Host(`${PHPMYADMIN_URL_PREFIX:-phpmyadmin.}${NETWORK_DOMAIN}`)
      traefik.http.routers.phpmyadmin.tls.certresolver: dns-cloudflare
      # Frontend => Services
      traefik.http.routers.phpmyadmin.service: phpmyadmin
      traefik.http.services.phpmyadmin.loadbalancer.server.port: 80

networks:
  mysql-workbench:
