include:
  - ../../networks/proxy_private.yaml

services:
  logforge.backend:
    image: madanb13/logforge-backend:latest@sha256:c349b0386d5dbb891c8dd0efb970762035de02bf16180932db0028d8d51967b8
    container_name: logforge.backend
    environment:
      PORT: "${BACKEND_SERVICE_PORT:-8000}"
      NOTIFIER_SERVICE_CONTAINER_NAME: "${NOTIFIER_SERVICE_CONTAINER_NAME:-logforge.notifier}"
      NOTIFIER_PLAIN_PORT: "${NOTIFIER_PLAIN_PORT:-8083}"
    networks:
      - logforge
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /srv/application_data/logforge/backend/data:/app/core/data
    restart: always
    ports:
      - "${EXPOSED_BACKEND_PORT:-8000}:${BACKEND_SERVICE_PORT:-8000}"
