services:
  logforge.frontend:
    image: madanb13/logforge-frontend:latest@sha256:e56c8af019ad48d115a50ad0a3e5fcc7f848b5da0ed72fa3c45680e421454ce0
    container_name: ${FRONTEND_SERVICE_CONTAINER_NAME:-logforge.frontend}
    environment:
      VITE_BACKEND_SERVICE_HOST: "http://${BACKEND_SERVICE_CONTAINER_NAME:-logforge.backend}"
      VITE_BACKEND_SERVICE_PORT: "${BACKEND_SERVICE_PORT:-8000}"
      VITE_EXPOSED_BACKEND_PORT: "${EXPOSED_BACKEND_PORT:-8000}"
      VITE_NOTIFIER_PORT: "${NOTIFIER_WEB_PORT:-8085}"
    ports:
      - "${EXPOSED_FRONTEND_PORT:-3000}:${FRONTEND_SERVICE_PORT:-3000}"
    networks:
      - proxy_private
      - logforge
    depends_on:
      - logforge.backend
    labels:
      diun.enable: "true"
      traefik.enable: "true"
      # Frontend => Router
      traefik.http.routers.logforge.entrypoints: websecure
      traefik.http.routers.logforge.rule: Host(`${LOGFORGE_URL_PREFIX:-logforge.}${NETWORK_DOMAIN}`)
      traefik.http.routers.logforge.tls.certresolver: dns-cloudflare
      # Frontend => Services
      traefik.http.routers.logforge.service: logforge
      traefik.http.services.logforge.loadbalancer.server.port: 3000
