services:
  logforge.notifier:
    image: madanb13/logforge-notifier:latest@sha256:9d7231f2d8cbc8bd02cbc6e4ee8bf708c6ab09fd46c7c5dd72fc714a638f25c7
    container_name: ${NOTIFIER_SERVICE_CONTAINER_NAME:-logforge.notifier}
    ports:
      - "${NOTIFIER_PLAIN_PORT:-8083}:8083"
      - "${NOTIFIER_WEB_PORT:-8085}:8085"
    volumes:
      - /srv/application_data/logforge/notifier/data:/app/data
      - /etc/localtime:/etc/localtime:ro
    networks:
      - logforge
    restart: unless-stopped
    labels:
      diun.enable: "true"
