include:
  - ../../networks/proxy_private.yaml
  - ../../volumes/smb-multimedia.yaml

services:
  radarr:
    image: ghcr.io/linuxserver/radarr:5.26.2
    container_name: radarr
    restart: unless-stopped
    networks:
      - proxy_private
    volumes:
      - smb.multimedia:/multimedia
      - /srv/application_data/radarr/app/config:/config
      - radarr.data.mediacover:/config/MediaCover
      - /srv/application_data/arr-discord-notifier/arr-discord-notifier.sh:/app/arr-discord-notifier.sh:ro
    environment:
      DISCORD_WEBHOOK: ${RADARR_DISCORD_WEBHOOK}
      AUTHOR_NAME: Radarr
      DROP_FIELDS: "rating,genres,cast,links,backdrop,release,overview,codecs"
      DOCKER_MODS: linuxserver/mods:universal-package-install
      INSTALL_PACKAGES: grep
      PUID: ${UID:-1000}
      PGID: ${GID:-1000}
      TZ: ${TIMEZONE}
    labels:
      # Glance
      glance.name: Radarr
      glance.icon: sh:radarr
      glance.url: https://${RADARR_URL_PREFIX:-radarr.}${NETWORK_DOMAIN}
      glance.description: Movie library management
      glance.category: media-management
      # What's Up Docker
      wud.watch: true
      wud.watch.digest: false
      wud.display.icon: sh:radarr
      wud.tag.include: ^\d+\.\d+\.\d+$$
      # Traefik
      traefik.enable: "true"
      # Traefik, Router
      traefik.http.routers.radarr.entrypoints: websecure
      traefik.http.routers.radarr.rule: Host(`${RADARR_URL_PREFIX:-radarr.}${NETWORK_DOMAIN}`)
      traefik.http.routers.radarr.tls.certresolver: dns-cloudflare
      traefik.http.routers.radarr.middlewares: forwardAuth-authentik@file
      # Traefik, Services
      traefik.http.routers.radarr.service: radarr
      traefik.http.services.radarr.loadbalancer.server.port: 7878

volumes:
  radarr.data.mediacover:
    driver_opts:
      type: nfs
      o: addr=10.0.0.10,nolock,soft,rw
      device: :/mnt/storage/application_data/radarr/app/config/MediaCover
