include:
  - ../../networks/proxy_private.yaml
  - ../../volumes/smb-multimedia.yaml

services:
  sonarr:
    image: ghcr.io/linuxserver/sonarr:4.0.15
    container_name: sonarr
    restart: unless-stopped
    networks:
      - proxy_private
    volumes:
      - smb.multimedia:/multimedia
      - /srv/application_data/sonarr/app/config:/config
      - sonarr.data.mediacover:/config/MediaCover
      #- $USERDIR/docker/shared/mp4_automator:/config_mp4_automator
      - /srv/application_data/arr-discord-notifier/arr-discord-notifier.sh:/app/arr-discord-notifier.sh:ro
    environment:
      DISCORD_WEBHOOK: ${SONARR_DISCORD_WEBHOOK}
      AUTHOR_NAME: Sonarr
      DROP_FIELDS: "rating,genres,cast,links,backdrop,release,overview,codecs"
      DOCKER_MODS: linuxserver/mods:universal-package-install
      INSTALL_PACKAGES: grep
      PUID: ${UID:-1000}
      PGID: ${GID:-1000}
      TZ: ${TIMEZONE}
    labels:
      # What's Up Docker
      wud.watch: true
      wud.watch.digest: false
      wud.link.template: https://github.com/Sonarr/Sonarr/releases
      wud.display.icon: sh:sonarr
      wud.tag.include: ^\d+\.\d+\.\d+$$
      # Traefik
      traefik.enable: "true"
      # Traefik, Router
      traefik.http.routers.sonarr.entrypoints: websecure
      traefik.http.routers.sonarr.rule: Host(`${SONARR_URL_PREFIX:-sonarr.}${NETWORK_DOMAIN}`)
      traefik.http.routers.sonarr.tls.certresolver: dns-cloudflare
      traefik.http.routers.sonarr.middlewares: forwardAuth-authentik@file
      # Traefik, Services
      traefik.http.routers.sonarr.service: sonarr
      traefik.http.services.sonarr.loadbalancer.server.port: 8989

volumes:
  sonarr.data.mediacover:
    driver_opts:
      type: nfs
      o: addr=10.0.0.10,nolock,soft,rw
      device: :/mnt/storage/application_data/sonarr/app/config/MediaCover
