include:
  - ../../networks/proxy_private.yaml

services:
  grocy:
    image: ghcr.io/linuxserver/grocy:4.5.0
    container_name: grocy
    restart: unless-stopped
    networks:
      - proxy_private
    volumes:
      - /srv/application_data/grocy/app/config:/config
    environment:
      PUID: ${UID:-1000}
      PGID: ${GID:-1000}
      TZ: ${TIMEZONE}
    labels:
      # Glance
      glance.name: Grocy
      glance.icon: sh:grocy
      glance.url: https://${GROCY_URL_PREFIX:-grocy.}${NETWORK_DOMAIN}
      glance.description: Home inventory
      glance.category: personal
      # What's Up Docker
      wud.watch: true
      wud.watch.digest: false
      wud.display.icon: sh:grocy
      wud.tag.include: ^\d+\.\d+\.\d+$$
      # Traefik
      traefik.enable: "true"
      # Traefik, Router
      traefik.http.routers.grocy.entrypoints: websecure
      traefik.http.routers.grocy.rule: Host(`${GROCY_URL_PREFIX:-grocy.}${NETWORK_DOMAIN}`)
      traefik.http.routers.grocy.tls.certresolver: dns-cloudflare
      traefik.http.routers.grocy.middlewares: forwardAuth-authentik@file
      # Traefik, Services
      traefik.http.routers.grocy.service: grocy
      traefik.http.services.grocy.loadbalancer.server.port: 80
