include:
  - ../../networks/proxy_private.yaml

services:
  grocy:
    image: ghcr.io/linuxserver/grocy:v4.5.0-ls293@sha256:ba512dd15c7ec8f3bf432c599710f4c05c6fe420963a298d410a078a4e6dd466
    container_name: grocy
    restart: unless-stopped
    networks:
      - proxy_private
    volumes:
      - /srv/application_data/grocy/app/config:/config
    environment:
      - PUID=${UID:-1000}
      - PGID=${GID:-1000}
      - TZ=${TIMEZONE}
    labels:
      diun.enable: "true"
      traefik.enable: "true"
      # Frontend => Router
      traefik.http.routers.grocy.entrypoints: websecure
      traefik.http.routers.grocy.rule: Host(`${GROCY_URL_PREFIX:-grocy.}${NETWORK_DOMAIN}`)
      traefik.http.routers.grocy.tls.certresolver: dns-cloudflare
      # Frontend => Services
      traefik.http.routers.grocy.service: grocy
      traefik.http.services.grocy.loadbalancer.server.port: 80
