include:
  - ../../networks/proxy_private.yaml

services:
  overseerr:
    image: ghcr.io/linuxserver/overseerr:1.34.0
    container_name: overseerr
    restart: unless-stopped
    networks:
      - proxy_private
    volumes:
      - /srv/application_data/overseerr/app/config:/config
    environment:
      PUID: ${UID:-1000}
      PGID: ${GID:-1000}
      TZ: ${TIMEZONE}
      #?- UMASK_SET=022 #optional
    labels:
      # What's Up Docker
      wud.watch: true
      wud.watch.digest: false
      wud.display.icon: sh:overseerr
      wud.tag.include: ^\d+\.\d+\.\d+$$
      wud.tag.exclude: ^\d{4}\.\d{2}\.\d{2}$$
      # Traefik
      traefik.enable: "true"
      # Traefik, Router
      traefik.http.routers.overseerr.entrypoints: websecure
      traefik.http.routers.overseerr.rule: Host(`${OVERSEERR_URL_PREFIX:-overseerr.}${NETWORK_DOMAIN}`)
      traefik.http.routers.overseerr.tls.certresolver: dns-cloudflare
      # Traefik, Services
      traefik.http.routers.overseerr.service: overseerr
      traefik.http.services.overseerr.loadbalancer.server.port: 5055
