include:
  - ../../networks/proxy_private.yaml

services:
  overseerr:
    image: ghcr.io/linuxserver/overseerr:v1.34.0-ls142@sha256:1205b8873f3ea0a98890191d9e01da911d9509272462a46414ba0378a6d76288
    container_name: overseerr
    restart: unless-stopped
    networks:
      - proxy_private
    volumes:
      - /srv/application_data/overseerr/app/config:/config
    environment:
      PUID: ${UID:-1000}
      PGID: ${GID:-1000}
      TZ: ${TIMEZONE}
      #?- UMASK_SET=022 #optional
    labels:
      diun.enable: "true"
      traefik.enable: "true"
      # Frontend => Router
      traefik.http.routers.overseerr.entrypoints: websecure
      traefik.http.routers.overseerr.rule: Host(`${OVERSEERR_URL_PREFIX:-overseerr.}${NETWORK_DOMAIN}`)
      traefik.http.routers.overseerr.tls.certresolver: dns-cloudflare
      # Frontend => Services
      traefik.http.routers.overseerr.service: overseerr
      traefik.http.services.overseerr.loadbalancer.server.port: 5055
