services:
  authentik.outpost:
    image: ghcr.io/goauthentik/proxy:2025.8.1
    container_name: authentik.outpost
    restart: unless-stopped
    environment:
      AUTHENTIK_HOST: https://auth.${NETWORK_DOMAIN}
      AUTHENTIK_TOKEN: ${AUTHENTIK_TOKEN}
      AUTHENTIK_INSECURE: "false"  # set to "true" if your Authentik domain uses self-signed certs
    networks:
      - proxy_private
    labels:
      # Glance
      glance.name: Authentik Outpost
      glance.icon: sh:authentik
      glance.description: Authentication outpost
      glance.category: core
