services:
  whoami:
    image: traefik/whoami
    container_name: whoami
    command:
       - --name=whoami
    networks:
      - proxy_private
    labels:
      traefik.enable: "true"
      # traefik.docker.network: dev
      # Frontend => Router
      traefik.http.routers.whoami.entrypoints: websecure
      traefik.http.routers.whoami.rule: Host(`whoami.enceladus.${NETWORK_DOMAIN}`)
      traefik.http.routers.whoami.tls.certresolver: dns-cloudflare
      traefik.http.routers.whoami.middlewares: forwardAuth-authentik@file # <--- this is the relevant part
      # Frontend => Services
      traefik.http.routers.whoami.service: whoami
      traefik.http.services.whoami.loadbalancer.server.port: 80