[[stack]]
name = "orb"
tags = ["tools"]
[stack.config]
server = "hyperion"
links = [
  "https://orb.net/docs/setup-sensor/docker",
  "https://hub.docker.com/r/orbforge/orb"
]
poll_for_updates = true
auto_update = true
git_account = "jekotia"
repo = "jekotia/saturn"
branch = "master"
webhook_enabled = false
run_directory = "docker/stacks/orb/"
file_paths = [
  "compose.yaml"
]