services:
  seafile.md-server:
    image: ${MD_IMAGE:-seafileltd/seafile-md-server:13.0-latest}
    container_name: seafile.md-server
    restart: unless-stopped
    volumes:
      - /mnt/storage/application_data/seafile/server/data:/shared
    # ports:
    #  - 8084:8084
    environment:
      - JWT_PRIVATE_KEY=${JWT_PRIVATE_KEY:?Variable is not set or empty}
      - SEAFILE_MYSQL_DB_HOST=seafile.database
      - SEAFILE_MYSQL_DB_PORT=3306
      - SEAFILE_MYSQL_DB_USER=seafile
      - SEAFILE_MYSQL_DB_PASSWORD=${SEAFILE_MYSQL_DB_PASSWORD:?Variable is not set or empty}
      - SEAFILE_MYSQL_DB_SEAFILE_DB_NAME=seafile_db
      - SEAFILE_LOG_TO_STDOUT=${SEAFILE_LOG_TO_STDOUT:-false}
      - MD_PORT=8084
      - MD_LOG_LEVEL=${MD_LOG_LEVEL:-info}
      - MD_MAX_CACHE_SIZE=${MD_MAX_CACHE_SIZE:-1GB}
      - MD_CHECK_UPDATE_INTERVAL=${MD_CHECK_UPDATE_INTERVAL:-30m}
      - MD_FILE_COUNT_LIMIT=${MD_FILE_COUNT_LIMIT:-100000}
      - SEAF_SERVER_STORAGE_TYPE=disk
      - MD_STORAGE_TYPE=disk
      - CACHE_PROVIDER=redis
      - REDIS_HOST=seafile.redis
      - REDIS_PORT=6379
    depends_on:
      seafile.database:
        condition: service_healthy
      seafile.server:
        condition: service_healthy

    networks:
      - seafile
