include:
  - ../../networks/proxy_private.yaml

services:
  navidrome:
    image: ghcr.io/navidrome/navidrome:0.56.1
    container_name: navidrome
    restart: unless-stopped
    user: ${UID:-568}:${GID:-1001} # should be owner of volumes
    networks:
    - proxy_private
    environment:
      ND_DATAFOLDER: /data
      ND_MUSICFOLDER: /music
      ND_BASEURL: https://${NAVIDROME_URL_PREFIX:-navidrome.}${NETWORK_DOMAIN}
      ND_REVERSEPROXYUSERHEADER: "X-authentik-username"
      ND_REVERSEPROXYWHITELIST: 0.0.0.0/0 # Potentially bypassable via an external reverse proxy
    volumes:
    - "/mnt/storage/application_data/navidrome/app/data:/data"
    - "/mnt/storage/multimedia/music:/music:ro"
    labels:
      # What's Up Docker
      wud.watch: true
      wud.watch.digest: false
      wud.display.icon: sh:navidrome
      wud.tag.include: ^\d+\.\d+\.\d+$$
      # Traefik
      traefik.enable: "true"
      # Traefik, Router
      traefik.http.routers.navidrome.entrypoints: websecure
      traefik.http.routers.navidrome.rule: Host(`${NAVIDROME_URL_PREFIX:-navidrome.}${NETWORK_DOMAIN}`)
      traefik.http.routers.navidrome.tls.certresolver: dns-cloudflare
      traefik.http.routers.navidrome.middlewares: forwardAuth-authentik@file
      # Traefik, Services
      traefik.http.routers.navidrome.service: navidrome
      traefik.http.services.navidrome.loadbalancer.server.port: 4533
