include:
  - ../../networks/proxy_private.yaml

services:
  navidrome:
    image: ghcr.io/navidrome/navidrome:0.56.1@sha256:d8dcacba4cf48b4caa81f231f20ebba719e642b0f86a46b1b5c24bb4f27edddc
    container_name: navidrome
    restart: unless-stopped
    user: ${UID:-568}:${GID:-1001} # should be owner of volumes
    networks:
    - proxy_private
    environment:
      ND_DATAFOLDER: /data
      ND_MUSICFOLDER: /music
      ND_BASEURL: https://${NAVIDROME_URL_PREFIX:-navidrome.}${NETWORK_DOMAIN}
      ND_REVERSEPROXYUSERHEADER: "X-authentik-username"
      ND_REVERSEPROXYWHITELIST: ${NAVIDROME_REVERSE_PROXY_WHITELIST}
    volumes:
    - "/mnt/storage/application_data/navidrome/app/data:/data"
    - "/mnt/storage/multimedia/music:/music:ro"
    labels:
      diun.enable: "true"
      traefik.enable: "true"
      # Frontend => Router
      traefik.http.routers.navidrome.entrypoints: websecure
      traefik.http.routers.navidrome.rule: Host(`${NAVIDROME_URL_PREFIX:-navidrome.}${NETWORK_DOMAIN}`)
      traefik.http.routers.navidrome.tls.certresolver: dns-cloudflare
      traefik.http.routers.navidrome.middlewares: forwardAuth-authentik@file
      # Frontend => Services
      traefik.http.routers.navidrome.service: navidrome
      traefik.http.services.navidrome.loadbalancer.server.port: 4533
