include:
  - ../../networks/proxy_private.yaml
  - ../../volumes/smb-multimedia.yaml

services:
  kavita:
    image: jvmilazz0/kavita:0.8.7
    container_name: kavita
    restart: unless-stopped
    networks:
      - proxy_private
    volumes:
      - smb.multimedia:/multimedia
      - /srv/application_data/kavita/app/config:/kavita/config
    environment:
      TZ: ${TIMEZONE}
    labels:
      # Glance
      glance.name: Kavita
      glance.icon: sh:kavita
      glance.url: https://${KAVITA_URL_PREFIX:-kavita.}${NETWORK_DOMAIN}
      glance.description: eBook library
      glance.category: media-server
      # What's Up Docker
      wud.watch: true
      wud.watch.digest: false
      wud.display.icon: sh:kavita
      wud.tag.include: ^\d+\.\d+\.\d+$$
      # Traefik
      traefik.enable: "true"
      # Traefik, Router
      traefik.http.routers.kavita.entrypoints: websecure
      traefik.http.routers.kavita.rule: Host(`${KAVITA_URL_PREFIX:-kavita.}${NETWORK_DOMAIN}`)
      traefik.http.routers.kavita.tls.certresolver: dns-cloudflare
      # Traefik, Services
      traefik.http.routers.kavita.service: kavita
      traefik.http.services.kavita.loadbalancer.server.port: 5000
  