services:
  kavita.email:
    image: kizaing/kavitaemail:0.1.20@sha256:754dfa15eddea50d04419f3cbe41f7bb7a19f19ddd5a5ed72248ba7c59094ae9
    container_name: kavita.email
    restart: unless-stopped
    environment:
      SMTP_HOST: ${KAVITA_MAIL_SMTP_HOST}
      SMTP_PORT: ${KAVITA_MAIL_SMTP_PORT}
      SMTP_USER: ${KAVITA_MAIL_SMTP_USER}
      SMTP_PASS: ${KAVITA_MAIL_SMTP_PASS}
      SEND_ADDR: ${KAVITA_MAIL_SEND_ADDR}
      DISP_NAME: Kavita
      # <true/false if you want the service to email files for Kavita>
      ALLOW_SENDTO: "true"
      #SIZE_LIMIT=<size in bytes that your SMTP provider can hanlde for a sinle email>
      #ports:
      #   - "5003:5003"
