[[stack]]
name = "kavita"
tags = ["media-server"]
[stack.config]
server = "hyperion"
links = [
  "https://kavita.jekotia.net",
  "https://github.com/Kareadita/Kavita",
  "https://hub.docker.com/r/jvmilazz0/kavita",
  "https://hub.docker.com/r/jvmilazz0/kavitaemail"
]
git_account = "jekotia"
repo = "jekotia/saturn"
branch = "master"
webhook_enabled = false
run_directory = "docker/stacks/kavita/"
file_paths = [
  "compose.yaml",
  "../../networks/proxy_private.yaml",
  "../../volumes/smb-multimedia.yaml"
]
environment = """
TIMEZONE=[[TIMEZONE]]

# KAVITA_URL_PREFIX=
NETWORK_DOMAIN=[[NETWORK_DOMAIN]]

MULTIMEDIA_HOST=[[MULTIMEDIA_HOST]]
MULTIMEDIA_USER=[[MULTIMEDIA_USER]]
MULTIMEDIA_PASS=[[MULTIMEDIA_PASS]]
"""