include:
  - ../../networks/proxy_private.yaml

services:
  # https://hub.docker.com/r/linuxserver/vscodium
  vscodium:
    image: lscr.io/linuxserver/vscodium:latest
    container_name: vscodium
    restart: always
    cap_add:
      - IPC_LOCK
    security_opt:
      - seccomp:unconfined #optional
    shm_size: "1gb"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TIMEZONE}
      - PROXY_DOMAIN=${VSCODIUM_URL_PREFIX:-vscodium.}${NETWORK_DOMAIN} #optional
      - DEFAULT_WORKSPACE=/srv/repositories
      - TITLE=vscodium
      - NODECOR=true
    volumes:
      - /srv/application_data/vscodium/app/config:/config
      - /srv/repositories:/srv/repositories
      - /home/jekotia/.zsh:/srv/zsh
      # - /home/jekotia/ssh/id_jameli:/config/.ssh/id_rsa #ssh key for GitHub integration
    networks:
      - proxy_private
    labels:
      traefik.enable: "true"
      # Frontend => Router
      traefik.http.routers.vscodium.entrypoints: websecure
      traefik.http.routers.vscodium.rule: Host(`${VSCODIUM_URL_PREFIX:-vscodium.}${NETWORK_DOMAIN}`)
      traefik.http.routers.vscodium.tls.certresolver: dns-cloudflare
      # Frontend => Services
      traefik.http.routers.vscodium.service: vscodium
      traefik.http.services.vscodium.loadbalancer.server.port: 3000
