[[stack]]
name = "vscodium"
tags = ["dev"]
[stack.config]
server = "hyperion"
links = [
  "https://vscodium.jekotia.net",
  "https://github.com/linuxserver/docker-vscodium",
  "https://github.com/linuxserver/docker-vscodium/pkgs/container/vscodium"
]
git_account = "jekotia"
repo = "jekotia/saturn"
branch = "master"
webhook_enabled = false
run_directory = "docker/stacks/vscodium/"
file_paths = [
  "compose.yaml",
  "../../networks/proxy_private.yaml"
]
environment = """
TIMEZONE=[[TIMEZONE]]

# VSCODIUM_URL_PREFIX=
NETWORK_DOMAIN=[[NETWORK_DOMAIN]]
"""
