include:
  - ../../networks/proxy_private.yaml

services:
  convertx:
    image: ghcr.io/c4illin/convertx:latest
    container_name: convertx
    restart: unless-stopped
    networks:
      - proxy_private
    volumes:
      - /srv/application_data/convertx/app/data:/app/data
    environment:
      ALLOW_UNAUTHENTICATED: true
      AUTO_DELETE_EVERY_N_HOURS: 48
    labels:
      # Glance
      glance.name: ConvertX
      glance.icon: sh:convertx
      glance.url: https://${CONVERTX_URL_PREFIX:-convertx.}${NETWORK_DOMAIN}
      glance.description: File conversion tools
      glance.category: tools
      # Traefik
      traefik.enable: "true"
      # Traefik, Router
      traefik.http.routers.convertx.entrypoints: websecure
      traefik.http.routers.convertx.rule: Host(`${CONVERTX_URL_PREFIX:-convertx.}${NETWORK_DOMAIN}`)
      traefik.http.routers.convertx.tls.certresolver: dns-cloudflare
      traefik.http.routers.convertx.middlewares: forwardAuth-authentik@file
      # Traefik, Services
      traefik.http.routers.convertx.service: convertx
      traefik.http.services.convertx.loadbalancer.server.port: 3000
