include:
  - ../../networks/proxy_private.yaml

services:
  prowlarr:
    image: ghcr.io/linuxserver/prowlarr:1.37.0.5076-ls120@sha256:b058be8a4e083e0cba238f03759994617a559abe0c89e5ed66454b44395da6a9
    container_name: prowlarr
    restart: unless-stopped
    networks:
      - proxy_private
    volumes:
      - /srv/application_data/prowlarr/app/config:/config
    environment:
      PUID: ${UID:-1000}
      PGID: ${GID:-1000}
      TZ: ${TIMEZONE}
    labels:
      diun.enable: "true"
      traefik.enable: "true"
      # Frontend => Router
      traefik.http.routers.prowlarr.entrypoints: websecure
      traefik.http.routers.prowlarr.rule: Host(`${PROWLARR_URL_PREFIX:-prowlarr.}${NETWORK_DOMAIN}`)
      traefik.http.routers.prowlarr.tls.certresolver: dns-cloudflare
      traefik.http.routers.prowlarr.middlewares: forwardAuth-authentik@file
      # Frontend => Services
      traefik.http.routers.prowlarr.service: prowlarr
      traefik.http.services.prowlarr.loadbalancer.server.port: 9696
