include:
  - ../../networks/proxy_private.yaml

services:
  prowlarr:
    image: ghcr.io/linuxserver/prowlarr:1.31.2.4975-ls107@sha256:761f73534a01aec4bf72a1396e9b9fda3f01632948b3fa31985982d26120a330
    container_name: prowlarr
    restart: unless-stopped
    networks:
      - proxy_private
    volumes:
      - /srv/application_data/prowlarr/app/config:/config
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TIMEZONE}
    labels:
      traefik.enable: "true"
      # Frontend => Router
      traefik.http.routers.prowlarr.entrypoints: websecure
      traefik.http.routers.prowlarr.rule: Host(`${PROWLARR_URL_PREFIX:-prowlarr.}${NETWORK_DOMAIN}`)
      traefik.http.routers.prowlarr.tls.certresolver: dns-cloudflare
      # Frontend => Services
      traefik.http.routers.prowlarr.service: prowlarr
      traefik.http.services.prowlarr.loadbalancer.server.port: 9696
