include:
  - ../../networks/proxy_private.yaml

services:
  prowlarr:
    image: ghcr.io/linuxserver/prowlarr:1.37.0
    container_name: prowlarr
    restart: unless-stopped
    networks:
      - proxy_private
    volumes:
      - /srv/application_data/prowlarr/app/config:/config
    environment:
      PUID: ${UID:-1000}
      PGID: ${GID:-1000}
      TZ: ${TIMEZONE}
    labels:
      # What's Up Docker
      wud.watch: true
      wud.watch.digest: false
      wud.display.icon: sh:prowlarr
      wud.tag.include: ^\d+\.\d+\.\d+$$
      # Traefik
      traefik.enable: "true"
      # Traefik, Router
      traefik.http.routers.prowlarr.entrypoints: websecure
      traefik.http.routers.prowlarr.rule: Host(`${PROWLARR_URL_PREFIX:-prowlarr.}${NETWORK_DOMAIN}`)
      traefik.http.routers.prowlarr.tls.certresolver: dns-cloudflare
      traefik.http.routers.prowlarr.middlewares: forwardAuth-authentik@file
      # Traefik, Services
      traefik.http.routers.prowlarr.service: prowlarr
      traefik.http.services.prowlarr.loadbalancer.server.port: 9696
