[[stack]]
name = "prowlarr"
tags = ["media-management"]
[stack.config]
server = "hyperion"
links = [
  "https://prowlarr.jekotia.net",
  "https://github.com/linuxserver/docker-prowlarr",
  "https://github.com/linuxserver/docker-prowlarr/pkgs/container/prowlarr"
]
git_account = "jekotia"
repo = "jekotia/saturn"
branch = "master"
webhook_enabled = false
run_directory = "docker/stacks/prowlarr/"
file_paths = [
  "compose.yaml",
  "../../networks/proxy_private.yaml"
]
environment = """
TIMEZONE=[[TIMEZONE]]

# PROWLARR_URL_PREFIX=
NETWORK_DOMAIN=[[NETWORK_DOMAIN]]

# UID=
# GID=
"""