[[stack]]
name = "lunalytics"
tags = ["core"]
[stack.config]
server = "hyperion"
links = [
  "https://lunalytics.jekotia.net",
  "https://github.com/KSJaay/Lunalytics",
  "https://hub.docker.com/r/ksjaay/Lunalytics"
]
git_account = "jekotia"
repo = "jekotia/saturn"
branch = "master"
webhook_enabled = false
run_directory = "docker/stacks/lunalytics/"
file_paths = [
  "compose.yaml",
  "app.yaml",
  "database.yaml",
  "../../networks/proxy_private.yaml"
]
environment = """
# LUNALYTICS_URL_PREFIX=
NETWORK_DOMAIN=[[NETWORK_DOMAIN]]

# POSTGRES_DB=
# POSTGRES_USER=
POSTGRES_PASSWORD=[[LUNALYTICS_POSTGRES_PASSWORD]]
"""