[[stack]]
name = "omni-tools"
tags = ["tools"]
[stack.config]
server = "hyperion"
links = [
  "https://omni-tools.jekotia.net",
  "https://github.com/iib0011/omni-tools",
  "https://hub.docker.com/r/iib0011/omni-tools"
]
poll_for_updates = true
auto_update = true
git_account = "jekotia"
repo = "jekotia/saturn"
branch = "master"
webhook_enabled = false
run_directory = "docker/stacks/omni-tools/"
file_paths = [
  "compose.yaml",
  "../../networks/proxy_private.yaml"
]
environment = """
# OMNITOOLS_URL_PREFIX=
NETWORK_DOMAIN=[[NETWORK_DOMAIN]]
"""