include:
  - ../../networks/proxy_private.yaml
  
services:
  qbittorrent:
    image: ghcr.io/linuxserver/qbittorrent:5.1.0
    container_name: qbittorrent
    restart: unless-stopped
    networks:
    - proxy_private
    ports:
    - 6881:6881
    - 6881:6881/udp
    volumes:
    - /mnt/storage/multimedia:/multimedia
    - /mnt/storage/application_data/qbittorrent/app/config:/config
    environment:
      PUID: ${UID:-568}
      PGID: ${GID:-1001}
      TZ: America/Toronto
      WEBUI_PORT: 8080
    #?- UMASK_SET=022
    labels:
      # What's Up Docker
      wud.watch: true
      wud.watch.digest: false
      wud.display.icon: sh:qbittorrent
      wud.tag.include: ^\d+\.\d+\.\d+$$
      # https://github.com/qbittorrent/qBittorrent/wiki/Traefik-Reverse-Proxy-for-Web-UI
      # Traefik
      traefik.enable: "true"
      # Traefik, Router
      traefik.http.routers.qbittorrent.entrypoints: websecure
      traefik.http.routers.qbittorrent.rule: Host(`${QBITTORRENT_URL_PREFIX:-qbittorrent.}${NETWORK_DOMAIN}`)
      traefik.http.routers.qbittorrent.tls.certresolver: dns-cloudflare
      traefik.http.routers.qbittorrent.middlewares: qbittorrent-headers
      # Traefik, Services
      traefik.http.routers.qbittorrent.service: qbittorrent
      traefik.http.services.qbittorrent.loadbalancer.server.port: 8080
      traefik.http.services.qbittorrent.loadbalancer.passhostheader: false
      # Traefik, Middlewares
      traefik.http.middlewares.qbittorrent-headers.headers.customrequestheaders.X-Frame-Options: SAMEORIGIN
      traefik.http.middlewares.qbittorrent-headers.headers.customrequestheaders.Referer:
      traefik.http.middlewares.qbittorrent-headers.headers.customrequestheaders.Origin:
