include:
  - ../../networks/proxy_private.yaml
  
services:
  qbittorrent:
    image: ghcr.io/linuxserver/qbittorrent:5.1.0-r0-ls397@sha256:22dc2f60b6253356005b6cbb77ea282c788aa9ffb828ca61c43479735913e02c
    container_name: qbittorrent
    restart: unless-stopped
    networks:
    - proxy_private
    ports:
    - 6881:6881
    - 6881:6881/udp
    volumes:
    - /mnt/storage/multimedia:/multimedia
    - /mnt/storage/application_data/qbittorrent/app/config:/config
    environment:
      PUID: ${UID:-568}
      PGID: ${GID:-1001}
      TZ: America/Toronto
      WEBUI_PORT: 8080
    #?- UMASK_SET=022
    labels:
      diun.enable: "true"
      traefik.enable: "true"
      # Frontend => Router
      traefik.http.routers.qbittorrent.entrypoints: websecure
      traefik.http.routers.qbittorrent.rule: Host(`${QBITTORRENT_URL_PREFIX:-qbittorrent.}${NETWORK_DOMAIN}`)
      traefik.http.routers.qbittorrent.tls.certresolver: dns-cloudflare
      # Frontend => Services
      traefik.http.routers.qbittorrent.service: qbittorrent
      traefik.http.services.qbittorrent.loadbalancer.server.port: 8080
      # https://github.com/qbittorrent/qBittorrent/wiki/Traefik-Reverse-Proxy-for-Web-UI
      # appropriate header changes
      traefik.http.middlewares.qbittorrent-headers.headers.customrequestheaders.X-Frame-Options: SAMEORIGIN
      traefik.http.middlewares.qbittorrent-headers.headers.customrequestheaders.Referer:
      traefik.http.middlewares.qbittorrent-headers.headers.customrequestheaders.Origin:
      traefik.http.routers.qbittorrent.middlewares: qbittorrent-headers
      # loadbalancer to *not* pass the host header
      traefik.http.services.qbittorrent.loadbalancer.passhostheader: false
