services:
  spotizerr.app:
    image: cooldockerizer93/spotizerr:3.0.1
    container_name: spotizerr.app
    restart: unless-stopped
    depends_on:
      - redis
    networks:
      - proxy_private
      - spotizerr
    volumes:
      - smb.multimedia:/multimedia
      - /srv/application_data/spotizerr/app/data:/app/data
      # - /srv/application_data/spotizerr/app/downloads:/app/downloads  # <-- Change this for your music library dir
      - /srv/application_data/spotizerr/app/logs:/app/logs  # <-- Volume for persistent logs
    environment:
      HOST: 0.0.0.0 # Interface to bind to. Unless you know what you're doing, don't change this
      PUID: 1000
      PGID: 1000
      UMASK: 0022
      REDIS_HOST: spotizerr.redis
      REDIS_PORT: 6379
      REDIS_DB: ${REDIS_DB}
      REDIS_URL: redis://:spotizerr.redis:6379/0
      REDIS_BACKEND: redis://:spotizerr.redis:6379/0
      EXPLICIT_FILTER: false
      ENABLE_AUTH: ${ENABLE_AUTH} # Set to true to enable authentication
      # JWT_SECRET: ${JWT_SECRET} # Set to a random string for production
      # JWT_EXPIRATION_HOURS: ${JWT_EXPIRATION_HOURS} # Set to 24 for 24 hours
      # DEFAULT_ADMIN_USERNAME: ${DEFAULT_ADMIN_USERNAME} # Set to admin
      # DEFAULT_ADMIN_PASSWORD: ${DEFAULT_ADMIN_PASSWORD} # Set to admin123
      # DISABLE_REGISTRATION: ${DISABLE_REGISTRATION} # Set to true to disable registration
    labels:
      # What's Up Docker
      wud.watch: true
      wud.watch.digest: false
      wud.link.template: https://github.com/Xoconoch/spotizerr/releases/tag/$${major}.$${minor}.$${patch}
      # wud.display.icon: 
      wud.tag.include: ^\d+\.\d+\.\d+$$
      # Traefik
      traefik.enable: "true"
      # Traefik, Router
      traefik.http.routers.spotizerr.entrypoints: websecure
      traefik.http.routers.spotizerr.rule: Host(`${SPOTIZERR_URL_PREFIX:-spotizerr.}${NETWORK_DOMAIN}`)
      traefik.http.routers.spotizerr.tls.certresolver: dns-cloudflare
      # traefik.http.routers.spotizerr.middlewares: forwardAuth-authentik@file
      # Traefik, Services
      traefik.http.routers.spotizerr.service: spotizerr
      traefik.http.services.spotizerr.loadbalancer.server.port: 7171
