services:
  spotizerr.app:
    image: cooldockerizer93/spotizerr:3.0.2
    container_name: spotizerr.app
    restart: unless-stopped
    depends_on:
      - spotizerr.redis
    networks:
      - proxy_private
      - spotizerr
    volumes:
      - /srv/application_data/spotizerr/app/data:/app/data
      - smb.multimedia:/app/downloads  # <-- Change this for your music library dir
      - /srv/application_data/spotizerr/app/logs:/app/logs  # <-- Volume for persistent logs
    environment:
      HOST: 0.0.0.0 # Interface to bind to. Unless you know what you're doing, don't change this
      PUID: ${UID:-1000}
      PGID: ${GID:-1000}
      # UMASK: "0022"
      REDIS_URL: redis://spotizerr.redis:6379/0
      REDIS_BACKEND: redis://spotizerr.redis:6379/0
      EXPLICIT_FILTER: false
      ENABLE_AUTH: false
    labels:
      # What's Up Docker
      wud.watch: true
      wud.watch.digest: false
      wud.link.template: https://github.com/Xoconoch/spotizerr/releases/tag/$${major}.$${minor}.$${patch}
      # wud.display.icon: 
      wud.tag.include: ^\d+\.\d+\.\d+$$
      # Traefik
      traefik.enable: "true"
      # Traefik, Router
      traefik.http.routers.spotizerr.entrypoints: websecure
      traefik.http.routers.spotizerr.rule: Host(`${SPOTIZERR_URL_PREFIX:-spotizerr.}${NETWORK_DOMAIN}`)
      traefik.http.routers.spotizerr.tls.certresolver: dns-cloudflare
      traefik.http.routers.spotizerr.middlewares: forwardAuth-authentik@file
      # Traefik, Services
      traefik.http.routers.spotizerr.service: spotizerr
      traefik.http.services.spotizerr.loadbalancer.server.port: 7171
