[[stack]]
name = "spotizerr"
tags = [
  "media-management",
  "smb-mounts"
]
[stack.config]
server = "hyperion"
links = [
  "https://spotizerr.jekotia.net",
  "https://github.com/Xoconoch/spotizerr",
  "https://hub.docker.com/r/cooldockerizer93/spotizerr"
]
git_account = "jekotia"
repo = "jekotia/saturn"
branch = "master"
webhook_enabled = false
run_directory = "docker/stacks/spotizerr/"
file_paths = [
  "compose.yaml",
  "app.yaml",
  "redis.yaml",
  "../../networks/proxy_private.yaml",
  "../../volumes/smb-multimedia.yaml"
]
environment = """
TIMEZONE=[[TIMEZONE]]

# SPOTIZERR_URL_PREFIX=
NETWORK_DOMAIN=[[NETWORK_DOMAIN]]

# UID=
# GID=

MULTIMEDIA_HOST=[[MULTIMEDIA_HOST]]
MULTIMEDIA_USER=[[MULTIMEDIA_USER]]
MULTIMEDIA_PASS=[[MULTIMEDIA_PASS]]
"""