services:
  nextcloud.cron:
    image: nextcloud:27-apache
    container_name: nextcloud.cron
    environment:
      NEXTCLOUD_DATA_DIR: ${NEXTCLOUD_DATA_DIR:-/storage}
      REDIS_HOST: nextcloud.redis
      NEXTCLOUD_ADMIN_USER: ${NEXTCLOUD_ADMIN_USER}
      NEXTCLOUD_ADMIN_PASS: ${NEXTCLOUD_ADMIN_PASS}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-nextcloud}
      MYSQL_USER: ${MYSQL_USER:-nextcloud}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_HOST: nextcloud.db:3306
    restart: always
    volumes:
      - app.data.storage:/storage
      - /srv/application_data/nextcloud/app/web:/var/www/html
    entrypoint: /cron.sh
    depends_on:
      - nextcloud.db
      - nextcloud.redis
    networks:
      - nextcloud
