services:
  nextcloud.db:
    image: mariadb:10.11.2-jammy
    container_name: nextcloud.db
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
      --innodb-read-only-compressed=OFF
    restart: always
    volumes:
      - /srv/application_data/nextcloud/db/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-nextcloud}
      MYSQL_USER: ${MYSQL_USER:-nextcloud}
      MARIADB_AUTO_UPGRADE: 1
      MARIADB_DISABLE_UPGRADE_BACKUP: 1
    networks:
      - nextcloud
    labels:
      # Glance
      glance.name: MariaDB
      glance.parent: nextcloud
      glance.category: personal
