[[stack]]
name = "mylar"
tags = [
  "media-management",
  "smb-mounts"
]
[stack.config]
server = "hyperion"
links = [
  "https://mylar.jekotia.net",
  "https://github.com/linuxserver/docker-mylar3",
  "https://github.com/linuxserver/docker-mylar3/pkgs/container/mylar3"
]
git_account = "jekotia"
repo = "jekotia/saturn"
branch = "master"
webhook_enabled = false
run_directory = "docker/stacks/mylar/"
file_paths = [
  "compose.yaml",
  "../../networks/proxy_private.yaml",
  "../../volumes/smb-multimedia.yaml"
]
environment = """
# MYLAR_URL_PREFIX=
TIMEZONE=[[TIMEZONE]]

NETWORK_DOMAIN=[[NETWORK_DOMAIN]]

MULTIMEDIA_HOST=[[MULTIMEDIA_HOST]]
MULTIMEDIA_USER=[[MULTIMEDIA_USER]]
MULTIMEDIA_PASS=[[MULTIMEDIA_PASS]]

# UID=
# GID=
"""