include:
  - ../../networks/proxy_private.yaml

services:
  github-pages:
    image: ghcr.io/jekotia/github-pages-chirpy:latest
    container_name: github-pages
    restart: unless-stopped
    networks:
      - proxy_private
    volumes:
      - /srv/repositories/jekotia.github.io:/src/site
    labels:
      # Glance
      glance.name: Github Pages
      glance.icon: sh:github-light
      glance.url: https://${GITHUB_PAGES_URL_PREFIX:-github-pages.}${NETWORK_DOMAIN}
      glance.description: Local test environment for jekotia.net
      glance.category: dev
      # Traefik
      traefik.enable: "true"
      # Traefik, Router
      traefik.http.routers.github-pages.entrypoints: websecure
      traefik.http.routers.github-pages.rule: Host(`${GITHUB_PAGES_URL_PREFIX:-github-pages.}${NETWORK_DOMAIN}`)
      traefik.http.routers.github-pages.tls.certresolver: dns-cloudflare
      # Traefik, Services
      traefik.http.routers.github-pages.service: github-pages
      traefik.http.services.github-pages.loadbalancer.server.port: 4000
