[[stack]]
name = "github-pages"
tags = ["dev"]
[stack.config]
server = "hyperion"
links = [
  "https://github-pages.jekotia.net",
  "https://github.com/Jekotia/jekotia.github.io",
  "https://github.com/Jekotia/Dockerfiles/pkgs/container/github-pages"
]
poll_for_updates = true
auto_update = true
git_account = "jekotia"
repo = "jekotia/saturn"
branch = "master"
webhook_enabled = false
run_directory = "docker/stacks/github-pages/"
file_paths = [
  "compose.yaml",
  "../../networks/proxy_private.yaml"
]
environment = """
# GITHUB_PAGES_URL_PREFIX=
NETWORK_DOMAIN=[[NETWORK_DOMAIN]]
"""