services:
  romm.app:
    image: ghcr.io/rommapp/romm:4.0.1
    container_name: romm.app
    restart: unless-stopped
    environment:
      DB_HOST: romm.db
      DB_NAME: ${ROMM_DB_NAME:-romm} # Should match MYSQL_DATABASE in mariadb
      DB_USER: ${ROMM_DB_USER:-romm} # Should match MYSQL_USER in mariadb
      DB_PASSWD: ${ROMM_DB_PASS} # Should match MYSQL_PASSWORD in mariadb
      ROMM_AUTH_SECRET_KEY: ${ROMM_AUTH_SECRET_KEY} # Generate a key with `openssl rand -hex 32`
      IGDB_CLIENT_ID: ${IGDB_ID} # Generate an ID and SECRET in IGDB
      IGDB_CLIENT_SECRET: ${IGDB_SECRET} # https://api-docs.igdb.com/#account-creation
      MOBYGAMES_API_KEY: ${MOBYGAMES_API_KEY} # https://www.mobygames.com/info/api/
      STEAMGRIDDB_API_KEY: ${STEAMGRID_API_KEY} # https://github.com/rommapp/romm/wiki/Generate-API-Keys#steamgriddb
      SCREENSCRAPER_USER: ${SCREENSCRAPER_USER} # Use your ScreenScraper username and password
      SCREENSCRAPER_PASSWORD: ${SCREENSCRAPER_PASSWORD} # https://docs.romm.app/latest/Getting-Started/Generate-API-Keys/#screenscraper
      # OIDC Configuration
      OIDC_ENABLED: true
      OIDC_PROVIDER: authentik
      OIDC_CLIENT_ID: ${OIDC_CLIENT_ID}
      OIDC_CLIENT_SECRET: ${OIDC_CLIENT_SECRET}
      OIDC_REDIRECT_URI: https://${ROMM_URL_PREFIX:-romm.}${NETWORK_DOMAIN}/api/oauth/openid
      OIDC_SERVER_APPLICATION_URL: https://auth.${NETWORK_DOMAIN}/application/o/${AUTHENTIK_SLUG:-romm}
    volumes:
      - /mnt/storage/application_data/romm/app/resources:/romm/resources # Resources fetched from IGDB (covers, screenshots, etc.)
      - /mnt/storage/application_data/romm/app/redis_data:/redis-data # Cached data for background tasks
      - /mnt/storage/games/roms:/romm/library # Your game library
      - /mnt/storage/application_data/romm/app/assets:/romm/assets # Uploaded saves, states, etc.
      - /mnt/storage/application_data/romm/app/config:/romm/config # Path where config.yml is stored
    depends_on:
      romm.db:
        condition: service_healthy
        restart: true
    networks:
      - proxy_private
      - romm
    labels:
      # Glance
      glance.name: RomM
      glance.icon: sh:romm
      glance.url: https://${ROMM_URL_PREFIX:-romm.}${NETWORK_DOMAIN}
      glance.description: ROM library manager & emulator
      glance.category: gaming
      glance.id: romm
      # What's Up Docker
      wud.watch: true
      wud.watch.digest: false
      wud.display.icon: sh:romm
      wud.tag.include: ^\d+\.\d+\.\d+$$
      # Traefik
      traefik.enable: "true"
      # Traefik, Router
      traefik.http.routers.romm.entrypoints: websecure
      traefik.http.routers.romm.rule: Host(`${ROMM_URL_PREFIX:-romm.}${NETWORK_DOMAIN}`)
      traefik.http.routers.romm.tls.certresolver: dns-cloudflare
      traefik.http.routers.romm.middlewares: romm_SharedArrayBuffer
      # Traefik, Services
      traefik.http.routers.romm.service: romm
      traefik.http.services.romm.loadbalancer.server.port: 8080
      # Traefik, Middlewares
      # Headers for MS-DOS/PPSSPP emulation
      traefik.http.middlewares.romm_SharedArrayBuffer.headers.customResponseHeaders.Cross-Origin-Opener-Policy: same-origin
      traefik.http.middlewares.romm_SharedArrayBuffer.headers.customResponseHeaders.Cross-Origin-Embedder-Policy: require-corp
