services:
  romm.db:
    # if you experience issues, try: linuxserver/mariadb:latest
    image: mariadb:11.5.2
    container_name: romm.db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${ROMM_DB_ROOT_PASS} # Use a unique, secure password
      MYSQL_DATABASE: ${ROMM_DB_NAME:-romm}
      MYSQL_USER: ${ROMM_DB_USER:-romm}
      MYSQL_PASSWORD: ${ROMM_DB_PASS}
    volumes:
      - /mnt/storage/application_data/romm/db/data:/var/lib/mysql
    networks:
      - romm
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 30s
      start_interval: 10s
      interval: 10s
      timeout: 5s
      retries: 5
    labels:
      # Glance
      glance.name: MariaDB
      glance.parent: romm
      glance.category: gaming
      # What's Up Docker
      wud.watch: true
      wud.watch.digest: false
      wud.display.icon: sh:mariadb
      wud.tag.include: ^\d+\.\d+\.\d+$$
