include:
  - ../../networks/proxy_private.yaml

services:
  status-overview:
    image: ghcr.io/github/pages-gem:master
    container_name: status-overview
    restart: unless-stopped
    command: [ "jekyll" , "serve" , "/src/site" , "--watch" , "--force_polling" , "--host" , "0.0.0.0" , "--port" , "4000" ]
    networks:
      - proxy_private
    volumes:
      - /srv/repositories/status-overview:/src/site
    labels:
      # Glance
      glance.name: Status Overview
      glance.icon: sh:ntfy
      glance.url: https://${STATUS_OVERVIEW_URL_PREFIX:-status-overview.}${NETWORK_DOMAIN}
      glance.description: ntfy status overview
      glance.category: core
      # Traefik
      traefik.enable: "true"
      # Traefik, Router
      traefik.http.routers.status-overview.entrypoints: websecure
      traefik.http.routers.status-overview.rule: Host(`${STATUS_OVERVIEW_URL_PREFIX:-status-overview.}${NETWORK_DOMAIN}`)
      traefik.http.routers.status-overview.tls.certresolver: dns-cloudflare
      # Traefik, Services
      traefik.http.routers.status-overview.service: status-overview
      traefik.http.services.status-overview.loadbalancer.server.port: 4000
