include:
  - ../../networks/proxy_private.yaml
  - ../../volumes/smb-multimedia.yaml
  
services:
  homepage:
    image: ghcr.io/gethomepage/homepage:v1.3.2@sha256:4f923bf0e9391b3a8bc5527e539b022e92dcc8a3a13e6ab66122ea9ed030e196
    container_name: homepage
    restart: always
    networks:
      - proxy_private
      - homepage.dockerproxy
    volumes:
      - /srv/application_data/homepage/app/config:/app/config # Make sure your local config directory exists
      - /srv/application_data/homepage/app/icons:/app/public/icons
      - smb.multimedia:/multimedia:ro
    environment:
    # Specify your user ID and group ID. You can find this by running `id -u` and `id -g`
      PUID: ${UID:-1000}
      PGID: ${GID:-1000}
      HOMEPAGE_ALLOWED_HOSTS: ${HOMEPAGE_URL_PREFIX:-homepage.}${NETWORK_DOMAIN}
    labels:
      traefik.enable: "true"
      # Frontend => Router
      traefik.http.routers.homepage.entrypoints: websecure
      traefik.http.routers.homepage.rule: Host(`${HOMEPAGE_URL_PREFIX:-homepage.}${NETWORK_DOMAIN}`)
      traefik.http.routers.homepage.tls.certresolver: dns-cloudflare
      traefik.http.routers.homepage.tls: "true"
      # Frontend => Services
      traefik.http.routers.homepage.service: homepage
      traefik.http.services.homepage.loadbalancer.server.port: "3000"

  homepage.dockerproxy:
    image: ghcr.io/tecnativa/docker-socket-proxy:latest
    container_name: homepage.dockerproxy
    environment:
      CONTAINERS: 1 # Allow access to viewing containers
      POST: 0 # Disallow any POST operations (effectively read-only)
    networks:
      - homepage.dockerproxy
    # ports:
    #   - 2375:2375
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro # Mounted as read-only
    restart: always

networks:
  homepage.dockerproxy:
