[[stack]]
name = "homepage"
tags = ["core"]
[stack.config]
server = "hyperion"
links = [
  "https://saturn.jekotia.net",
  "https://github.com/gethomepage/homepage",
  "https://github.com/gethomepage/homepage/pkgs/container/homepage"
]
poll_for_updates = true
auto_update = true
git_account = "jekotia"
repo = "jekotia/saturn"
branch = "master"
webhook_enabled = false
run_directory = "docker/stacks/homepage/"
file_paths = [
  "compose.yaml",
  "../../networks/proxy_private.yaml",
  "../../volumes/smb-multimedia.yaml"
]
environment = """
HOMEPAGE_URL_PREFIX=saturn.
NETWORK_DOMAIN=[[NETWORK_DOMAIN]]

MULTIMEDIA_HOST=[[MULTIMEDIA_HOST]]
MULTIMEDIA_USER=[[MULTIMEDIA_USER]]
MULTIMEDIA_PASS=[[MULTIMEDIA_PASS]]

# UID=
# GID=
"""