include:
  - ../../networks/proxy_private.yaml
  - ../../volumes/smb-multimedia.yaml

services:
  bazarr:
    image: ghcr.io/linuxserver/bazarr:v1.5.2-ls307@sha256:a92ba81b9405942d0b5c01e2707ba8fb99ab059dd800d1dc0e8f52f62ddf74dd
    container_name: bazarr
    restart: unless-stopped
    networks:
      - proxy_private
    volumes:
      - smb.multimedia:/multimedia
      - /srv/application_data/bazarr/app/config:/config
    environment:
      PUID: ${PID:-1000}
      PGID: ${GID:-1000}
      TZ: ${TIMEZONE}
    labels:
      diun.enable: "true"
      traefik.enable: "true"
      # Frontend => Router
      traefik.http.routers.bazarr.entrypoints: websecure
      traefik.http.routers.bazarr.rule: Host(`${BAZARR_URL_PREFIX:-bazarr.}${NETWORK_DOMAIN}`)
      traefik.http.routers.bazarr.tls.certresolver: dns-cloudflare
      traefik.http.routers.bazarr.middlewares: forwardAuth-authentik@file
      # Frontend => Services
      traefik.http.routers.bazarr.service: bazarr
      traefik.http.services.bazarr.loadbalancer.server.port: 6767
