include:
  - ../../networks/proxy_private.yaml
  - ../../volumes/smb-multimedia.yaml

services:
  bazarr:
    image: ghcr.io/linuxserver/bazarr:1.5.2
    container_name: bazarr
    restart: unless-stopped
    networks:
      - proxy_private
    volumes:
      - smb.multimedia:/multimedia
      - /srv/application_data/bazarr/app/config:/config
    environment:
      PUID: ${PID:-1000}
      PGID: ${GID:-1000}
      TZ: ${TIMEZONE}
    labels:
      # Glance
      glance.name: Bazarr
      glance.icon: sh:bazarr
      glance.url: https://${BAZARR_URL_PREFIX:-bazarr.}${NETWORK_DOMAIN}
      glance.description: Subtitle management
      glance.category: media-management
      # What's Up Docker
      wud.watch: true
      wud.watch.digest: false
      wud.display.icon: sh:bazarr
      wud.tag.include: ^\d+\.\d+\.\d+$$
      # Traefik
      traefik.enable: "true"
      # Traefik, Router
      traefik.http.routers.bazarr.entrypoints: websecure
      traefik.http.routers.bazarr.rule: Host(`${BAZARR_URL_PREFIX:-bazarr.}${NETWORK_DOMAIN}`)
      traefik.http.routers.bazarr.tls.certresolver: dns-cloudflare
      traefik.http.routers.bazarr.middlewares: forwardAuth-authentik@file
      # Traefik, Services
      traefik.http.routers.bazarr.service: bazarr
      traefik.http.services.bazarr.loadbalancer.server.port: 6767
