[[stack]]
name = "tdarr-server"
tags = ["media-management"]
[stack.config]
server = "hyperion"
links = [
  "https://tdarr.jekotia.net",
  "https://github.com/HaveAGitGat/Tdarr",
  "https://github.com/HaveAGitGat/Tdarr/pkgs/container/tdarr"
]
git_account = "jekotia"
repo = "jekotia/saturn"
branch = "master"
webhook_enabled = false
run_directory = "docker/stacks/tdarr-server/"
file_paths = [
  "compose.yaml",
  "../../networks/proxy_private.yaml",
  "../../volumes/smb-multimedia.yaml"
]
environment = """
TIMEZONE=[[TIMEZONE]]

NETWORK_DOMAIN=[[NETWORK_DOMAIN]]

TDARR_SERVER_IP=10.0.0.20
TDARR_NODE_NAME=Hyperion

MULTIMEDIA_HOST=[[MULTIMEDIA_HOST]]
MULTIMEDIA_USER=[[MULTIMEDIA_USER]]
MULTIMEDIA_PASS=[[MULTIMEDIA_PASS]]

# UID=
# GID=
"""