services:
  karakeep.app:
    image: ghcr.io/karakeep-app/karakeep:0.25.0@sha256:572076596ea7fdaa189694d31dc8059743773b1f908d68d7c4af3737948ff3b3
    container_name: karakeep.app
    restart: unless-stopped
    networks:
      - karakeep
      - proxy_private
    volumes:
      - /srv/application_data/karakeep/app/data:/data
    environment:
      MEILI_ADDR: http://karakeep.meilisearch:7700
      BROWSER_WEB_URL: http://karakeep.chrome:9222
      #OPENAI_API_KEY: ${OPENAI_API_KEY}

      OLLAMA_BASE_URL: http://draewyn.saturn.jekotia.net:11434
      # Make sure to pull the models in ollama first. Example models:
      INFERENCE_TEXT_MODEL: gemma3
      INFERENCE_IMAGE_MODEL: llava
      # If the model you're using doesn't support structured output, you also need:
      # INFERENCE_OUTPUT_SCHEMA=plain

      # You almost never want to change the value of the DATA_DIR variable.
      # If you want to mount a custom directory, change the volume mapping above instead.
      DATA_DIR: /data # DON'T CHANGE THIS
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
      MEILI_MASTER_KEY: ${MEILI_MASTER_KEY}
      NEXTAUTH_URL: ${NEXTAUTH_URL:-http://localhost:3000}
    labels:
      diun.enable: "true"
      traefik.enable: "true"
      # Frontend => Router
      traefik.http.routers.karakeep.entrypoints: websecure
      traefik.http.routers.karakeep.rule: Host(`${KARAKEEP_URL_PREFIX:-karakeep.}${NETWORK_DOMAIN}`)
      traefik.http.routers.karakeep.tls.certresolver: dns-cloudflare
      # Frontend => Services
      traefik.http.routers.karakeep.service: karakeep
      traefik.http.services.karakeep.loadbalancer.server.port: 3000
