include:
  - ../../networks/proxy_private.yaml
  
services:
  ntfy:
    image: binwiederhier/ntfy:v2.11.0@sha256:4a7d0f0adc6d5d9fc36e64ab55ef676e76e124a2bdd50ce115b6d9c1c7430294
    container_name: ntfy
    restart: always
    command:
      - serve
    user: 1000:1000 # optional: replace with your own user/group or uid/gid
    networks:
      - proxy_private
    volumes:
      - /srv/application_data/ntfy/app/cache:/var/cache/ntfy
      - /srv/application_data/ntfy/app/etc:/etc/ntfy
    environment:
      - TZ=${TIMEZONE}    # optional: set desired timezone
    healthcheck: # optional: remember to adapt the host:port to your environment
        test: ["CMD-SHELL", "wget -q --tries=1 http://localhost:80/v1/health -O - | grep -Eo '\"healthy\"\\s*:\\s*true' || exit 1"]
        interval: 60s
        timeout: 10s
        retries: 3
        start_period: 40s
    labels:
      - "traefik.enable=true"
      # Frontend => Router
      - "traefik.http.routers.ntfy.entrypoints=websecure"
      - "traefik.http.routers.ntfy.rule=Host(`${NTFY_URL_PREFIX:-ntfy.}${NETWORK_DOMAIN}`)"
      - "traefik.http.routers.ntfy.tls.certresolver=dns-cloudflare"
      - "traefik.http.routers.ntfy.tls=true"
      # Frontend => Services
      - "traefik.http.routers.ntfy.service=ntfy"
      - "traefik.http.services.ntfy.loadbalancer.server.port=80"
