include:
  - ../../networks/proxy_private.yaml

services:
  ntfy:
    image: binwiederhier/ntfy:v2.14.0
    container_name: ntfy
    restart: always
    command:
      - serve
    user: 1000:1000 # optional: replace with your own user/group or uid/gid
    networks:
      - proxy_private
    volumes:
      - /srv/application_data/ntfy/app/cache:/var/cache/ntfy
      - /srv/application_data/ntfy/app/etc:/etc/ntfy
    environment:
      TZ: ${TIMEZONE}    # optional: set desired timezone
    healthcheck: # optional: remember to adapt the host:port to your environment
        test: ["CMD-SHELL", "wget -q --tries=1 http://localhost:80/v1/health -O - | grep -Eo '\"healthy\"\\s*:\\s*true' || exit 1"]
        interval: 60s
        timeout: 10s
        retries: 3
        start_period: 40s
    labels:
      # What's Up Docker
      wud.watch: true
      wud.watch.digest: false
      wud.link.template: https://github.com/binwiederhier/ntfy/releases/tag/v$${major}.$${minor}.$${patch}
      wud.display.icon: sh:ntfy
      wud.tag.include: ^v\d+\.\d+\.\d+$$
      # Traefik
      traefik.enable: "true"
      # Traefik, Router
      traefik.http.routers.ntfy.entrypoints: websecure
      traefik.http.routers.ntfy.rule: Host(`${NTFY_URL_PREFIX:-ntfy.}${NETWORK_DOMAIN}`)
      traefik.http.routers.ntfy.tls.certresolver: dns-cloudflare
      traefik.http.routers.ntfy.tls: "true"
      # Traefik, Services
      traefik.http.routers.ntfy.service: ntfy
      traefik.http.services.ntfy.loadbalancer.server.port: 80
