[[stack]]
name = "ntfy"
tags = ["core"]
[stack.config]
server = "hyperion"
links = [
  "https://ntfy.jekotia.net",
  "https://github.com/binwiederhier/ntfy",
  "https://hub.docker.com/r/binwiederhier/ntfy"
]
git_account = "jekotia"
repo = "jekotia/saturn"
branch = "master"
webhook_enabled = false
run_directory = "docker/stacks/ntfy/"
file_paths = [
  "compose.yaml",
  "../../networks/proxy_private.yaml"
]
environment = """
TIMEZONE=[[TIMEZONE]]

# NTFY_URL_PREFIX=
NETWORK_DOMAIN=[[NETWORK_DOMAIN]]
"""