include:
  - ../../networks/proxy_private.yaml
  - ../../volumes/smb-multimedia.yaml

services:
  lidarr:
    image: ghcr.io/linuxserver/lidarr:2.12.4
    container_name: lidarr
    restart: unless-stopped
    networks:
      - proxy_private
    volumes:
      - smb.multimedia:/multimedia
      - /srv/application_data/lidarr/app/config:/config
      - lidarr.data.Backups:/config/Backups
      - lidarr.data.mediacover:/config/MediaCover
    environment:
      PUID: ${UID:-1000}
      PGID: ${GID:-1000}
      TZ: ${TIMEZONE}
      # UMASK_SET: 022 #optional
    labels:
      # What's Up Docker
      wud.watch: true
      wud.watch.digest: false
      wud.display.icon: sh:lidarr
      wud.tag.include: ^\d+\.\d+\.\d+$$
      # Traefik
      traefik.enable: "true"
      # Traefik, Router
      traefik.http.routers.lidarr.entrypoints: websecure
      traefik.http.routers.lidarr.rule: Host(`${LIDARR_URL_PREFIX:-lidarr.}${NETWORK_DOMAIN}`)
      traefik.http.routers.lidarr.tls.certresolver: dns-cloudflare
      traefik.http.routers.lidarr.middlewares: forwardAuth-authentik@file
      # Traefik, Services
      traefik.http.routers.lidarr.service: lidarr
      traefik.http.services.lidarr.loadbalancer.server.port: 8686

volumes:
  lidarr.data.Backups:
    driver_opts:
      type: nfs
      o: addr=10.0.0.10,nolock,soft,rw
      device: :/mnt/storage/application_data/lidarr/app/config/Backups
  lidarr.data.mediacover:
    driver_opts:
      type: nfs
      o: addr=10.0.0.10,nolock,soft,rw
      device: :/mnt/storage/application_data/lidarr/app/config/MediaCover
