include:
  - ../../networks/proxy_private.yaml
  - ../../volumes/smb-multimedia.yaml

services:
  lidarr:
    image: ghcr.io/linuxserver/lidarr:2.12.4.4658-ls45@sha256:71fe6d5702691c6ac8961b9b1042fdea1ff833a49c82c5e165346fa88999a48a
    container_name: lidarr
    restart: unless-stopped
    networks:
      - proxy_private
    volumes:
      - smb.multimedia:/multimedia
      - /srv/application_data/lidarr/app/config:/config
      - lidarr.data.Backups:/config/Backups
      - lidarr.data.mediacover:/config/MediaCover
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TIMEZONE}
      #?- UMASK_SET=022 #optional
    labels:
      diun.enable: "true"
      traefik.enable: "true"
      # Frontend => Router
      traefik.http.routers.lidarr.entrypoints: websecure
      traefik.http.routers.lidarr.rule: Host(`${LIDARR_URL_PREFIX:-lidarr.}${NETWORK_DOMAIN}`)
      traefik.http.routers.lidarr.tls.certresolver: dns-cloudflare
      # Frontend => Services
      traefik.http.routers.lidarr.service: lidarr
      traefik.http.services.lidarr.loadbalancer.server.port: 8686

volumes:
  lidarr.data.Backups:
    driver_opts:
      type: nfs
      o: addr=10.0.0.10,nolock,soft,rw
      device: :/mnt/storage/application_data/lidarr/app/config/Backups
  lidarr.data.mediacover:
    driver_opts:
      type: nfs
      o: addr=10.0.0.10,nolock,soft,rw
      device: :/mnt/storage/application_data/lidarr/app/config/MediaCover
