[[stack]]
name = "lidarr"
tags = ["media-management"]
[stack.config]
server = "hyperion"
links = [
  "https://lidarr.jekotia.net",
  "https://github.com/linuxserver/docker-lidarr",
  "https://github.com/linuxserver/docker-lidarr/pkgs/container/lidarr"
]
git_account = "jekotia"
repo = "jekotia/saturn"
branch = "master"
webhook_enabled = false
run_directory = "docker/stacks/lidarr/"
file_paths = [
  "compose.yaml",
  "../../networks/proxy_private.yaml",
  "../../volumes/smb-multimedia.yaml"
]
environment = """
TIMEZONE=[[TIMEZONE]]

# LIDARR_URL_PREFIX=
NETWORK_DOMAIN=[[NETWORK_DOMAIN]]

MULTIMEDIA_HOST=[[MULTIMEDIA_HOST]]
MULTIMEDIA_USER=[[MULTIMEDIA_USER]]
MULTIMEDIA_PASS=[[MULTIMEDIA_PASS]]
"""