include:
  - ../../networks/proxy_private.yaml

services:
  ttrss.app:
    image: wangqiru/ttrss:latest-2022-12-23@sha256:b1c3cc789a3c251f5bf7fc682246935facb099cf615bbdf817b553f0f7f7ef7d
    container_name: ttrss.app
    environment:
      - SELF_URL_PATH=https://${TTRSS_URL_PREFIX:-ttrss.}${NETWORK_DOMAIN}/
      - DB_HOST=ttrss.db
      - DB_PORT=5432
      - DB_NAME=${DB_NAME:-ttrss}
      - DB_USER=${DB_USER:-postgres}
      - DB_PASS=${POSTGRES_PASSWORD} # please change the password
      - ENABLE_PLUGINS=auth_internal,fever # auth_internal is required. Plugins enabled here will be enabled for all users as system plugins
    stdin_open: true
    tty: true
    restart: unless-stopped
    #command: sh -c 'sh /wait-for.sh $$DB_HOST:$$DB_PORT -- php /configure-db.php && exec s6-svscan /etc/s6/'
    networks:
      - proxy_private
      - ttrss
    depends_on:
      - ttrss.db
    labels:
      traefik.enable: "true"
      # Frontend => Router
      traefik.http.routers.ttrss.entrypoints: websecure
      traefik.http.routers.ttrss.rule: Host(`${TTRSS_URL_PREFIX:-ttrss.}${NETWORK_DOMAIN}`)
      traefik.http.routers.ttrss.tls.certresolver: dns-cloudflare
      # Frontend => Services
      traefik.http.routers.ttrss.service: ttrss
      traefik.http.services.ttrss.loadbalancer.server.port: 80
