services:
  app:
    image: cthulhoo/ttrss-fpm-pgsql-static:${RELEASE_TAG}
    container_name: ttrss.app
    restart: unless-stopped
    networks:
      - ttrss
    env_file:
      - .env
    volumes:
      - /srv/application_data/ttrss/app/html:/var/www/html
      - /srv/application_data/ttrss/app/config.d:/opt/tt-rss/config.d:ro
    depends_on:
      - db
    labels:
      # Glance
      glance.name: Tiny Tiny RSS
      glance.icon: sh:tiny-tiny-rss
      glance.url: https://${TTRSS_URL_PREFIX:-ttrss.}${NETWORK_DOMAIN}
      glance.description: RSS feed reader
      glance.category: general
      # What's Up Docker
      wud.watch: true
      wud.watch.digest: false
      wud.display.icon: sh:tiny-tiny-rss
