services:
  db:
    image: postgres:17.5-alpine
    container_name: ttrss.db
    restart: unless-stopped
    networks:
      - ttrss
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${TTRSS_DB_USER}
      - POSTGRES_PASSWORD=${TTRSS_DB_PASS}
      - POSTGRES_DB=${TTRSS_DB_NAME}
    volumes:
      - /srv/application_data/ttrss/db/data:/var/lib/postgresql/data
    labels:
      # What's Up Docker
      wud.watch: true
      wud.watch.digest: false
      wud.display.icon: sh:postgresql
      wud.tag.include: ^\d+\.\d+-alpine$$
