services:
  updater:
    image: cthulhoo/ttrss-fpm-pgsql-static:851ddf4b
    container_name: ttrss.updater
    restart: unless-stopped
    networks:
      - ttrss
    env_file:
      - .env
    volumes:
      - /srv/application_data/ttrss/app/html:/var/www/html
      - /srv/application_data/ttrss/app/config.d:/opt/tt-rss/config.d:ro
    depends_on:
      - app
    command: /opt/tt-rss/updater.sh
    labels:
      # What's Up Docker
      wud.watch: true
      wud.watch.digest: false
      wud.display.icon: sh:tiny-tiny-rss
