services:
  web-nginx:
    image: cthulhoo/ttrss-web-nginx:851ddf4b@sha256:ac920266f55bb8e3659dfb435a944b2dbddca50780d02a46684f2e9e6543ef64
    container_name: ttrss.web-nginx
    restart: unless-stopped
    networks:
      - proxy_private
      - ttrss
    env_file:
      - .env
    volumes:
      - /srv/application_data/ttrss/app/html:/var/www/html:ro
    depends_on:
      - app
    labels:
      #diun.enable: "true"
      traefik.enable: "true"
      # Frontend => Router
      traefik.http.routers.ttrss.entrypoints: websecure
      traefik.http.routers.ttrss.rule: Host(`${TTRSS_URL_PREFIX:-ttrss.}${NETWORK_DOMAIN}`)
      traefik.http.routers.ttrss.tls.certresolver: dns-cloudflare
      # Frontend => Services
      traefik.http.routers.ttrss.service: ttrss
      traefik.http.services.ttrss.loadbalancer.server.port: 80