[[resource_sync]]
name = "saturn"
[resource_sync.config]
repo = "jekotia/saturn"
branch = "master"
git_account = "jekotia"
webhook_enabled = false
resource_path = [
  "docker/stacks/",
  "komodo/"
]
delete = true
