include:
  - ../../networks/proxy_private.yaml

services:
  stirlingpdf:
    image: ghcr.io/stirling-tools/stirling-pdf:0.46.2@sha256:396ca949b81198a65b9abfec38518fa44e871b1970dad9f9718ffd030eef9b92
    container_name: stirlingpdf
    restart: unless-stopped
    environment:
      - DOCKER_ENABLE_SECURITY=${DOCKER_ENABLE_SECURITY:-false}
      - LANGS=${LANGS:-en_GB}
    networks:
      - proxy_private
    volumes:
      - /srv/application_data/stirlingpdf/app/trainingData:/usr/share/tessdata # Required for extra OCR languages
      - /srv/application_data/stirlingpdf/app/extraConfigs:/configs
      - /srv/application_data/stirlingpdf/app/customFiles:/customFiles/
      - /srv/application_data/stirlingpdf/app/logs:/logs/
      - /srv/application_data/stirlingpdf/app/pipeline:/pipeline/
    labels:
      traefik.enable: "true"
      # Frontend => Router
      traefik.http.routers.stirlingpdf.entrypoints: websecure
      traefik.http.routers.stirlingpdf.rule: Host(`${STIRLINGPDF_URL_PREFIX:-stirlingpdf.}${NETWORK_DOMAIN}`)
      traefik.http.routers.stirlingpdf.tls.certresolver: dns-cloudflare
      # Frontend => Services
      traefik.http.routers.stirlingpdf.service: stirlingpdf
      traefik.http.services.stirlingpdf.loadbalancer.server.port: 8080
