include:
  - ../../networks/proxy_private.yaml
  - ../../volumes/smb-multimedia.yaml

services:
  readarr:
    image: ghcr.io/linuxserver/readarr:0.4.18-develop
    container_name: readarr
    restart: unless-stopped
    networks:
      - proxy_private
    volumes:
      - smb.multimedia:/multimedia
      - /srv/application_data/readarr/app/config:/config
      - readarr.data.mediacover:/config/MediaCover
    environment:
      PUID: ${UID:-1000}
      PGID: ${GID:-1000}
      TZ: ${TIMEZONE}
    labels:
      # What's Up Docker
      wud.watch: true
      wud.watch.digest: false
      wud.display.icon: sh:readarr
      wud.tag.include: ^\d+\.\d+\.\d+-develop$$
      # Traefik
      traefik.enable: "true"
      # Traefik, Router
      traefik.http.routers.readarr.entrypoints: websecure
      traefik.http.routers.readarr.rule: Host(`${READARR_URL_PREFIX:-readarr.}${NETWORK_DOMAIN}`)
      traefik.http.routers.readarr.tls.certresolver: dns-cloudflare
      traefik.http.routers.readarr.middlewares: forwardAuth-authentik@file
      # Traefik, Services
      traefik.http.routers.readarr.service: readarr
      traefik.http.services.readarr.loadbalancer.server.port: 8787

volumes:
  readarr.data.mediacover:
    driver_opts:
      type: nfs
      o: addr=10.0.0.10,nolock,soft,rw
      device: :/mnt/storage/application_data/readarr/app/config/MediaCover
