include:
  - ../../networks/proxy_private.yaml
  - ../../volumes/smb-multimedia.yaml

services:
  readarr:
    image: ghcr.io/linuxserver/readarr:develop-0.4.17.2801-ls155@sha256:d71c575745ab4579ae0dbb4f91244cf9a74d7085d28a927218146466f8e6418c
    container_name: readarr
    restart: unless-stopped
    networks:
      - proxy_private
    volumes:
      - smb.multimedia:/multimedia
      - /srv/application_data/readarr/app/config:/config
      - readarr.data.mediacover:/config/MediaCover
    environment:
      PUID: ${UID:-1000}
      PGID: ${GID:-1000}
      TZ: ${TIMEZONE}
    labels:
      diun.enable: "true"
      diun.include_tags: "develop-.*"
      traefik.enable: "true"
      # Frontend => Router
      traefik.http.routers.readarr.entrypoints: websecure
      traefik.http.routers.readarr.rule: Host(`${READARR_URL_PREFIX:-readarr.}${NETWORK_DOMAIN}`)
      traefik.http.routers.readarr.tls.certresolver: dns-cloudflare
      traefik.http.routers.readarr.middlewares: forwardAuth-authentik@file
      # Frontend => Services
      traefik.http.routers.readarr.service: readarr
      traefik.http.services.readarr.loadbalancer.server.port: 8787

volumes:
  readarr.data.mediacover:
    driver_opts:
      type: nfs
      o: addr=10.0.0.10,nolock,soft,rw
      device: :/mnt/storage/application_data/readarr/app/config/MediaCover
