[[stack]]
name = "readarr"
tags = [
  "media-management",
  "smb-mounts"
]
[stack.config]
server = "hyperion"
links = [
  "https://readarr.jekotia.net",
  "https://github.com/linuxserver/docker-readarr",
  "https://github.com/linuxserver/docker-readarr/pkgs/container/readarr"
]
git_account = "jekotia"
repo = "jekotia/saturn"
branch = "master"
webhook_enabled = false
run_directory = "docker/stacks/readarr/"
file_paths = [
  "compose.yaml",
  "../../networks/proxy_private.yaml",
  "../../volumes/smb-multimedia.yaml"
]
environment = """
TIMEZONE=[[TIMEZONE]]

# READARR_URL_PREFIX=
NETWORK_DOMAIN=[[NETWORK_DOMAIN]]

MULTIMEDIA_HOST=[[MULTIMEDIA_HOST]]
MULTIMEDIA_USER=[[MULTIMEDIA_USER]]
MULTIMEDIA_PASS=[[MULTIMEDIA_PASS]]

# UID=
# GID=
"""