services:
  plextraktsync:
    image: ghcr.io/taxel/plextraktsync:0.34.11@sha256:ea2ffc8eff13b7ce43f482d5a6aee0f83c58828fb69e113a2b505440b275bb2b
    container_name: plextraktsync
    restart: no
    command: sync
    environment:
      PUID: ${UID:-1000}
      PGID: ${GID:-1000}
      TZ: ${TIMEZONE}
    volumes:
      - /srv/application_data/plextraktsync/app/config:/app/config
    labels:
      diun.enable: "true"
  