services:
  plextraktsync:
    image: ghcr.io/taxel/plextraktsync:0.34.11
    container_name: plextraktsync
    restart: no
    command: sync
    environment:
      PUID: ${UID:-1000}
      PGID: ${GID:-1000}
      TZ: ${TIMEZONE}
    volumes:
      - /srv/application_data/plextraktsync/app/config:/app/config
    labels:
      # What's Up Docker
      wud.watch: true
      wud.watch.digest: false
      wud.display.icon: sh:python
      wud.tag.include: ^\d+\.\d+\.\d+$$
  