include:
  - ../../networks/proxy_private.yaml
  
services:
  foundry:
    container_name: foundry
    image: ghcr.io/felddy/foundryvtt:13.346.0
    restart: unless-stopped
    environment:
      #FOUNDRY_VERSION=${_HYPERION_FOUNDRY_VERSION}
      FOUNDRY_PASSWORD: ${FOUNDRY_PASSWORD}
      FOUNDRY_USERNAME: ${FOUNDRY_USERNAME}
      FOUNDRY_LICENSE_KEY: ${FOUNDRY_LICENSE_KEY}
      FOUNDRY_ADMIN_KEY: ${FOUNDRY_ADMIN_KEY}
      CONTAINER_CACHE: /application_data/container_cache
      CONTAINER_PRESERVE_CONFIG: true
      FOUNDRY_HOSTNAME: ${FOUNDRY_URL_PREFIX:-foundry.}${NETWORK_DOMAIN}
      FOUNDRY_LOCAL_HOSTNAME: ${FOUNDRY_URL_PREFIX:-foundry.}${NETWORK_DOMAIN}
      FOUNDRY_PROXY_PORT: 443
      FOUNDRY_PROXY_SSL: true
      FOUNDRY_PROTOCOL: 4
      TIMEZONE: ${TIMEZONE}
    volumes:
      - /srv/application_data/foundry/app/data:/data:rw
      - foundry.data.container_cache:/application_data/container_cache
    networks:
      - proxy_private
    labels:
      # Glance
      glance.name: Foundry VTT
      glance.icon: sh:foundry-virtual-tabletop
      glance.url: https://${FOUNDRY_URL_PREFIX:-foundry.}${NETWORK_DOMAIN}
      glance.description: Virtual gaming tabletop
      glance.category: gaming
      # What's Up Docker
      wud.watch: true
      wud.link.template: https://github.com/felddy/foundryvtt-docker/releases/tag/v$${major}.$${minor}.$${patch}
      wud.watch.digest: false
      wud.display.icon: sh:foundry-virtual-tabletop
      wud.tag.include: ^\d+\.\d+\.\d+$$
      # Traefik
      traefik.enable: "true"
      # Traefik, Router
      traefik.http.routers.foundry.entrypoints: websecure
      traefik.http.routers.foundry.rule: Host(`${FOUNDRY_URL_PREFIX:-foundry.}${NETWORK_DOMAIN}`)
      traefik.http.routers.foundry.tls.certresolver: dns-cloudflare
      # Traefik, Services
      traefik.http.routers.foundry.service: foundry
      traefik.http.services.foundry.loadbalancer.server.port: 30000
volumes:
  foundry.data.container_cache:
    driver_opts:
      type: nfs
      o: addr=10.0.0.10,nolock,soft,rw
      device: :/mnt/storage/application_data/foundry/app/container_cache
