include:
  - ../../networks/proxy_private.yaml

services:
  portainer:
    container_name: portainer
    image: portainer/portainer-ee:latest
    restart: always
    command: -H unix:///var/run/docker.sock
    networks:
      - proxy_private
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /srv/application_data/portainer/app/data:/data # Change to local directory if you want to save/transfer config locally
    environment:
      TZ: ${TIMEZONE}
    labels:
      # Glance
      glance.name: Portainer
      glance.icon: sh:portainer
      glance.url: https://${PORTAINER_URL_PREFIX:-portainer.}${NETWORK_DOMAIN}
      glance.description: Docker resource management
      glance.category: core
      # Traefik
      traefik.enable: "true"
      # Traefik,. Router
      traefik.http.routers.portainer.entrypoints: websecure
      traefik.http.routers.portainer.rule: Host(`${PORTAINER_URL_PREFIX:-portainer.}${NETWORK_DOMAIN}`)
      traefik.http.routers.portainer.tls: "true"
      # Traefik, Services
      traefik.http.routers.portainer.service: portainer
      traefik.http.services.portainer.loadbalancer.server.port: 9000
