include:
  - ../../networks/proxy_private.yaml

services:
  bytestash:
    image: ghcr.io/jordan-dalby/bytestash:1.5.8
    container_name: bytestash
    restart: always
    environment:
      # See https://github.com/jordan-dalby/ByteStash/wiki/FAQ#environment-variables
      BASE_PATH: ""
      JWT_SECRET: ${BYTESTASH_JWT_SECRET}
      TOKEN_EXPIRY: 24h
      ALLOW_NEW_ACCOUNTS: "true"
      DEBUG: "false"
      DISABLE_ACCOUNTS: "false"
      DISABLE_INTERNAL_ACCOUNTS: "false"
      # See https://github.com/jordan-dalby/ByteStash/wiki/Single-Sign%E2%80%90on-Setup for more info
      #      OIDC_ENABLED: "false"
      #      OIDC_DISPLAY_NAME: ""
      #      OIDC_ISSUER_URL: ""
      #      OIDC_CLIENT_ID: ""
      #      OIDC_CLIENT_SECRET: ""
      #      OIDC_SCOPES: ""
    volumes:
      - /srv/application_data/bytestash/app/snippets:/data/snippets
    networks:
      - proxy_private
    labels:
      # Glance
      glance.name: Bytestash
      glance.icon: sh:bytestash
      glance.url: https://${BYTESTASH_URL_PREFIX:-bytestash.}${NETWORK_DOMAIN}
      glance.description: Code snippets
      glance.category: dev
      # What's Up Docker
      wud.watch: true
      wud.watch.digest: false
      wud.display.icon: sh:bytestash
      wud.tag.include: ^\d+\.\d+\.\d+$$
      # Traefik
      traefik.enable: "true"
      # Traefik, Router
      traefik.http.routers.bytestash.entrypoints: websecure
      traefik.http.routers.bytestash.rule: Host(`${BYTESTASH_URL_PREFIX:-bytestash.}${NETWORK_DOMAIN}`)
      traefik.http.routers.bytestash.tls.certresolver: dns-cloudflare
      # Traefik, Services
      traefik.http.routers.bytestash.service: bytestash
      traefik.http.services.bytestash.loadbalancer.server.port: 5000
