include:
  - ../../networks/proxy_private.yaml

services:
  13ft:
    image: ghcr.io/wasi-master/13ft:latest
    container_name: 13ft
    hostname: 13ft
    restart: unless-stopped
    networks:
      - proxy_private
    labels:
      # Glance
      glance.name: 13ft
      # glance.icon: sh:13ft
      glance.url: https://${THIRTEENFT_URL_PREFIX:-13ft.}${NETWORK_DOMAIN}
      glance.description: Paywall removal
      glance.category: tools
      # Traefik
      traefik.enable: "true"
      # Traefik, Router
      traefik.http.routers.13ft.entrypoints: websecure
      traefik.http.routers.13ft.rule: Host(`${THIRTEENFT_URL_PREFIX:-13ft.}${NETWORK_DOMAIN}`)
      traefik.http.routers.13ft.tls.certresolver: dns-cloudflare
      # Traefik, Services
      traefik.http.routers.13ft.service: 13ft
      traefik.http.services.13ft.loadbalancer.server.port: 5000
