services:
  paperless.broker:
    image: redis:8.2.0-alpine
    container_name: paperless.broker
    restart: unless-stopped
    networks:
      - paperless
    volumes:
      - /srv/application_data/paperless/broker/data:/data
    labels:
      # What's Up Docker
      wud.watch: true
      wud.watch.digest: false
      wud.display.icon: sh:redis
      wud.tag.include: ^\d+\.\d+\.\d+-alpine$$
