services:
  paperless.db:
    image: postgres:17.6-alpine
    container_name: paperless.db
    restart: unless-stopped
    networks:
      - paperless
    volumes:
      - /srv/application_data/paperless/db/data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-paperless}
      POSTGRES_USER: ${POSTGRES_USER:-paperless}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    labels:
      # Glance
      glance.name: PostgreSQL
      glance.parent: paperless
      glance.category: personal
      # What's Up Docker
      wud.watch: true
      wud.watch.digest: false
      wud.display.icon: sh:postgresql
      wud.tag.include: ^\d+\.\d+-alpine$$