services:
  paperless.gotenberg:
    image: gotenberg/gotenberg:8.21
    container_name: paperless.gotenberg
    restart: unless-stopped
    networks:
      - paperless
    # The gotenberg chromium route is used to convert .eml files. We do not
    # want to allow external content like tracking pixels or even javascript.
    command:
      - gotenberg
      - --chromium-disable-javascript=true
      - --chromium-allow-list=file:///tmp/.*
    labels:
      # Glance
      glance.name: Gotenberg
      glance.parent: paperless
      glance.category: personal
      # What's Up Docker
      wud.watch: true
      wud.watch.digest: false
      # wud.display.icon:
      wud.tag.include: ^\d+\.\d+$$