[[stack]]
name = "audiobookshelf"
tags = ["media-server"]
[stack.config]
server = "hyperion"
links = ["https://audiobookshelf.jekotia.net"]
git_account = "jekotia"
repo = "jekotia/saturn"
branch = "master"
webhook_enabled = false
run_directory = "docker/stacks/audiobookshelf/"
file_paths = [
  "compose.yaml",
  "../../networks/proxy_private.yaml",
  "../../volumes/smb-multimedia.yaml"
]
environment = """
NETWORK_DOMAIN=[[NETWORK_DOMAIN]]

MULTIMEDIA_HOST=[[MULTIMEDIA_HOST]]
MULTIMEDIA_USER=[[MULTIMEDIA_USER]]
MULTIMEDIA_PASS=[[MULTIMEDIA_PASS]]
"""