[[stack]]
name = "bazarr"
tags = ["media-management"]
[stack.config]
server = "hyperion"
links = ["https://bazarr.jekotia.net"]
git_account = "jekotia"
repo = "jekotia/saturn"
branch = "master"
webhook_enabled = false
run_directory = "docker/stacks/bazarr/"
file_paths = [
  "compose.yaml",
  "../../networks/proxy_private.yaml",
  "../../volumes/smb-multimedia.yaml"
]
environment = """
TIMEZONE=[[TIMEZONE]]

# BAZARR_URL_PREFIX=
NETWORK_DOMAIN=[[NETWORK_DOMAIN]]

# PID=
# GID=

MULTIMEDIA_HOST=[[MULTIMEDIA_HOST]]
MULTIMEDIA_USER=[[MULTIMEDIA_USER]]
MULTIMEDIA_PASS=[[MULTIMEDIA_PASS]]
"""