[[stack]]
name = "core-enceladus"
tags = ["enceladus"]
[stack.config]
server = "enceladus"
links = ["https://traefik.enceladus.jekotia.net"]
git_account = "jekotia"
repo = "jekotia/saturn"
branch = "master"
webhook_enabled = false
run_directory = "docker/stacks/core-enceladus/"
file_paths = [
  "compose.yaml",
  "portainer.yaml",
  "traefik.yaml",
  "../../networks/proxy_private.yaml"
]
pre_deploy.path = "/mnt/storage/application_data/traefik/app"
pre_deploy.command = """
mkdir acme
touch acme/acme.json
chmod 600 acme/acme.json
touch traefik.log
"""
environment = """
TIMEZONE=[[TIMEZONE]]

TRAEFIK_URL_PREFIX=traefik.enceladus.
NETWORK_DOMAIN=[[NETWORK_DOMAIN]]

SECRETS_CLOUDFLARE_API_KEY=[[ENCELADUS_TRAEFIK_CLOUDFLARE_API_TOKEN]]
SECRETS_CLOUDFLARE_EMAIL=[[SECRETS_CLOUDFLARE_EMAIL]]

# TRAEFIK_UID=
# TRAEFIK_GID=
"""