[[stack]]
name = "dozzle"
tags = ["core"]
[stack.config]
server = "hyperion"
links = ["https://dozzle.jekotia.net"]
git_account = "jekotia"
repo = "jekotia/saturn"
branch = "master"
webhook_enabled = false
run_directory = "docker/stacks/dozzle/"
file_paths = [
  "compose.yaml",
  "../../networks/proxy_private.yaml"
]
environment = """
# DOZZLE_URL_PREFIX=
NETWORK_DOMAIN=[[NETWORK_DOMAIN]]
"""