[[stack]]
name = "foundry"
tags = ["gaming"]
[stack.config]
server = "hyperion"
links = ["https://foundry.jekotia.net"]
git_account = "jekotia"
repo = "jekotia/saturn"
branch = "master"
webhook_enabled = false
run_directory = "docker/stacks/foundry/"
file_paths = [
  "compose.yaml",
  "../../networks/proxy_private.yaml"
]
environment = """
TIMEZONE=[[TIMEZONE]]

NETWORK_DOMAIN=[[NETWORK_DOMAIN]]

FOUNDRY_PASSWORD=[[FOUNDRY_PASSWORD]]
FOUNDRY_USERNAME=[[FOUNDRY_USERNAME]]
FOUNDRY_LICENSE_KEY=[[FOUNDRY_LICENSE_KEY]]
FOUNDRY_ADMIN_KEY=[[FOUNDRY_ADMIN_KEY]]
"""