[[stack]]
name = "kasm-vscode"
tags = ["dev"]
[stack.config]
server = "hyperion"
links = ["https://kasm-vscode.jekotia.net"]
git_account = "jekotia"
repo = "jekotia/saturn"
branch = "master"
webhook_enabled = false
run_directory = "docker/stacks/kasm-vscode/"
file_paths = [
  "compose.yaml",
  "../../networks/proxy_private.yaml"
]
environment = """
TIMEZONE=[[TIMEZONE]]

NETWORK_DOMAIN=[[NETWORK_DOMAIN]]

VNC_PASSWORD=[[KASM_VSCODE_VNC_PASSWORD]]
"""
