[[stack]]
name = "logforge"
tags = ["management"]
[stack.config]
server = "hyperion"
links = ["https://logforge.jekotia.net"]
git_account = "jekotia"
repo = "jekotia/saturn"
branch = "master"
webhook_enabled = false
run_directory = "docker/stacks/logforge/"
file_paths = [
  "compose.yaml",
  "../../networks/proxy_private.yaml"
]
environment = """
# LOGFORGE_URL_PREFIX=
NETWORK_DOMAIN=[[NETWORK_DOMAIN]]

BACKEND_SERVICE_CONTAINER_NAME="logforge.backend"
BACKEND_SERVICE_PORT="8000"
EXPOSED_BACKEND_PORT="8000"

FRONTEND_SERVICE_CONTAINER_NAME="logforge.frontend"
FRONTEND_SERVICE_PORT="3000"
EXPOSED_FRONTEND_PORT="3000"

NOTIFIER_SERVICE_CONTAINER="logforge.notifier"
NOTIFIER_PLAIN_PORT="8083"
NOTIFIER_WEB_PORT="8086"
"""