[[stack]]
name = "navidrome"
tags = ["media-server"]
[stack.config]
server = "enceladus"
links = ["https://navidrome.jekotia.net"]
git_account = "jekotia"
repo = "jekotia/saturn"
branch = "master"
webhook_enabled = false
run_directory = "docker/stacks/navidrome/"
file_paths = [
  "compose.yaml",
  "../../networks/proxy_private.yaml"
]
environment = """
# NAVIDROME_URL_PREFIX=
NETWORK_DOMAIN=[[NETWORK_DOMAIN]]

# UID=
# GID=
"""