[[stack]]
name = "omni-tools"
tags = ["utilities"]
[stack.config]
server = "hyperion"
links = ["https://omni-tools.jekotia.net"]
git_account = "jekotia"
repo = "jekotia/saturn"
branch = "master"
webhook_enabled = false
run_directory = "docker/stacks/omni-tools/"
file_paths = [
  "compose.yaml",
  "../../networks/proxy_private.yaml"
]
environment = """
# OMNITOOLS_URL_PREFIX=
NETWORK_DOMAIN=[[NETWORK_DOMAIN]]
"""