[[stack]]
name = "orb"
tags = ["tools"]
[stack.config]
server = "hyperion"
git_account = "jekotia"
repo = "jekotia/saturn"
branch = "master"
webhook_enabled = false
run_directory = "docker/stacks/orb/"
file_paths = [
  "compose.yaml"
]