[[stack]]
name = "overseerr"
tags = ["media-management"]
[stack.config]
server = "hyperion"
links = ["https://overseerr.jekotia.net"]
git_account = "jekotia"
repo = "jekotia/saturn"
branch = "master"
webhook_enabled = false
run_directory = "docker/stacks/overseerr/"
file_paths = [
  "compose.yaml",
  "../../networks/proxy_private.yaml"
]
environment = """
TIMEZONE=[[TIMEZONE]]

# OVERSEERR_URL_PREFIX=
NETWORK_DOMAIN=[[NETWORK_DOMAIN]]
"""