[[stack]]
name = "paperless"
tags = ["personal"]
[stack.config]
server = "hyperion"
links = ["https://paperless.jekotia.net"]
git_account = "jekotia"
repo = "jekotia/saturn"
branch = "master"
webhook_enabled = false
run_directory = "docker/stacks/paperless/"
file_paths = [
  "compose.yaml",
  "app.yaml",
  "broker.yaml",
  "database.yaml",
  "gotenberg.yaml",
  "tika.yaml",
  "../../networks/proxy_private.yaml"
]
environment = """
TIMEZONE=[[TIMEZONE]]

PAPERLESS_URL_PREFIX=paperless.
NETWORK_DOMAIN=[[NETWORK_DOMAIN]]

POSTGRES_PASSWORD=[[PAPERLESS_POSTGRES_PASSWORD]]

PAPERLESS_SMB_HOST=[[PAPERLESS_SMB_HOST]]
PAPERLESS_SMB_USER=[[PAPERLESS_SMB_USER]]
PAPERLESS_SMB_PASS=[[PAPERLESS_SMB_PASS]]
"""