[[stack]]
name = "portainer"
tags = ["core"]
[stack.config]
server = "hyperion"
links = ["https://portainer.jekotia.net"]
git_account = "jekotia"
repo = "jekotia/saturn"
branch = "master"
webhook_enabled = false
run_directory = "docker/stacks/portainer/"
file_paths = [
  "compose.yaml",
  "../../networks/proxy_private.yaml"
]
environment = """
TIMEZONE=[[TIMEZONE]]

NETWORK_DOMAIN=[[NETWORK_DOMAIN]]
"""