[[stack]]
name = "qbittorrent"
tags = ["media-management"]
[stack.config]
server = "enceladus"
links = ["https://qbittorrent.jekotia.net"]
git_account = "jekotia"
repo = "jekotia/saturn"
branch = "master"
webhook_enabled = false
run_directory = "docker/stacks/qbittorrent/"
file_paths = [
  "compose.yaml",
  "../../networks/proxy_private.yaml",
  "../../volumes/smb-multimedia.yaml"
]
environment = """
# QBITTORRENT_URL_PREFIX=
NETWORK_DOMAIN=[[NETWORK_DOMAIN]]
"""