[[stack]]
name = "romm"
tags = ["gaming"]
[stack.config]
server = "hyperion"
links = ["https://romm.jekotia.net"]
git_account = "jekotia"
repo = "jekotia/saturn"
branch = "master"
webhook_enabled = false
run_directory = "docker/stacks/romm/"
file_paths = [
  "compose.yaml",
  "app.yaml",
  "db.yaml",
  "../../networks/proxy_private.yaml"
]
environment = """
# ROMM_URL_PREFIX=
NETWORK_DOMAIN=[[NETWORK_DOMAIN]]

IGDB_ID=[[IGDB_ID]]
IGDB_SECRET=[[IGDB_SECRET]]
STEAMGRID_API_KEY=[[STEAMGRID_API_KEY]]
MOBYGAMES_API_KEY=[[MOBYGAMES_API_KEY]]
ROMM_AUTH_SECRET_KEY=[[ROMM_AUTH_SECRET_KEY]]
SCREENSCRAPER_USER=[[SCREENSCRAPER_USER]]
SCREENSCRAPER_PASSWORD=[[SCREENSCRAPER_PASSWORD]]

# ROMM_DB_NAME=
# ROMM_DB_USER=
ROMM_DB_PASS=[[ROMM_DB_PASS]]
ROMM_DB_ROOT_PASS=[[ROMM_DB_ROOT_PASS]]
"""