[[stack]]
name = "rustdesk"
tags = []
[stack.config]
server = "hyperion"
git_account = "jekotia"
repo = "jekotia/saturn"
branch = "master"
webhook_enabled = false
run_directory = "docker/stacks/rustdesk/"
file_paths = ["compose.yaml"]
environment = """
"""