[[stack]]
name = "sonarr"
tags = ["media-management"]
[stack.config]
server = "hyperion"
links = ["https://sonarr.jekotia.net"]
git_account = "jekotia"
repo = "jekotia/saturn"
branch = "master"
webhook_enabled = false
run_directory = "docker/stacks/sonarr/"
file_paths = [
  "compose.yaml",
  "../../networks/proxy_private.yaml",
  "../../volumes/smb-multimedia.yaml"
]
environment = """
TIMEZONE=[[TIMEZONE]]

# SONARR_URL_PREFIX=
NETWORK_DOMAIN=[[NETWORK_DOMAIN]]

SONARR_DISCORD_WEBHOOK=https://discord.com/api/webhooks/1129554718256005161/1yiJo0TSw3XYlpMLwu0yrPZX-NF7Z8qORkb127Ydw43__cJ5nk6ZccUOdT3uKtp_6iq1

MULTIMEDIA_HOST=[[MULTIMEDIA_HOST]]
MULTIMEDIA_USER=[[MULTIMEDIA_USER]]
MULTIMEDIA_PASS=[[MULTIMEDIA_PASS]]
"""