[[stack]]
name = "ttrss"
tags = ["personal"]
[stack.config]
server = "hyperion"
links = ["https://ttrss.jekotia.net"]
git_account = "jekotia"
repo = "jekotia/saturn"
branch = "master"
webhook_enabled = false
run_directory = "docker/stacks/ttrss/"
file_paths = [
  "compose.yaml",
  "app.yaml",
  "database.yaml",
  "../../networks/proxy_private.yaml"
]
environment = """
# TTRSS_URL_PREFIX=
NETWORK_DOMAIN=[[NETWORK_DOMAIN]]

# DB_NAME=
# DB_USER=
POSTGRES_PASSWORD=[[TTRSS_POSTGRES_PASSWORD]]
"""