[[stack]]
name = "uptime-kuma"
tags = ["core"]
[stack.config]
server = "hyperion"
links = ["https://uptime.jekotia.net"]
git_account = "jekotia"
repo = "jekotia/saturn"
branch = "master"
webhook_enabled = false
run_directory = "docker/stacks/uptime-kuma/"
file_paths = [
  "compose.yaml",
  "../../networks/proxy_private.yaml"
]
environment = """
# UPTIME_KUMA_URL_PREFIX=
NETWORK_DOMAIN=[[NETWORK_DOMAIN]]
"""