include:
  - ../../networks/proxy_private.yaml

services:
  resilio-sync:
    image: ghcr.io/linuxserver/resilio-sync:3.0.3.1065-1-ls213@sha256:9f330ccf779a53e651bbbb9dbcdaf703a6f591c94900493ee9a54b820368f1df
    container_name: resilio-sync
    restart: unless-stopped
    networks:
      - proxy_private
    ports:
      - 55555:55555 # sync port
    volumes:
      - /srv/application_data/resilio-sync/app/config:/config
      - smb.archive:/sync/archive
    environment:
      PUID: ${UID:-1000}
      PGID: ${GID:-1000}
      TZ: ${TIMEZONE}
    labels:
      diun.enable: "true"
      traefik.enable: "true"
      # Frontend => Router
      traefik.http.routers.resilio-sync.entrypoints: websecure
      traefik.http.routers.resilio-sync.rule: Host(`${RESILIO_SYNC_URL_PREFIX:-resilio-sync.}${NETWORK_DOMAIN}`)
      traefik.http.routers.resilio-sync.tls.certresolver: dns-cloudflare
      # Frontend => Services
      traefik.http.routers.resilio-sync.service: resilio-sync
      traefik.http.services.resilio-sync.loadbalancer.server.port: 8888

volumes:
  smb.archive:
    driver_opts:
      type: cifs
      o: username=${SMB_ARCHIVE_USER},password=${SMB_ARCHIVE_PASS},uid=1000,gid=1000
      device: //${SMB_ARCHIVE_HOST}/archive
