include:
  - ../../networks/proxy_private.yaml

services:
  resilio-sync:
    image: ghcr.io/linuxserver/resilio-sync:3.1.0
    container_name: resilio-sync
    restart: unless-stopped
    networks:
      - proxy_private
    ports:
      - 55555:55555 # sync port
    volumes:
      - /srv/application_data/resilio-sync/app/config:/config
      - smb.archive:/sync/archive
    environment:
      PUID: ${UID:-1000}
      PGID: ${GID:-1000}
      TZ: ${TIMEZONE}
    labels:
      # Glance
      glance.name: Resilio Sync
      glance.icon: sh:resilio-sync
      glance.url: https://${RESILIO_SYNC_URL_PREFIX:-resilio-sync.}${NETWORK_DOMAIN}
      glance.description: File syncronisation tool
      glance.category: backups
      # What's Up Docker
      wud.watch: true
      wud.watch.digest: false
      wud.link.template: https://help.resilio.com/hc/en-us/articles/31386579044755-Resilio-Sync-3-0-change-log
      wud.display.icon: sh:resilio-sync
      wud.tag.include: ^\d+\.\d+\.\d+$$
      # Traefik
      traefik.enable: "true"
      # Traefik, Router
      traefik.http.routers.resilio-sync.entrypoints: websecure
      traefik.http.routers.resilio-sync.rule: Host(`${RESILIO_SYNC_URL_PREFIX:-resilio-sync.}${NETWORK_DOMAIN}`)
      traefik.http.routers.resilio-sync.tls.certresolver: dns-cloudflare
      # Traefik, Services
      traefik.http.routers.resilio-sync.service: resilio-sync
      traefik.http.services.resilio-sync.loadbalancer.server.port: 8888

volumes:
  smb.archive:
    driver_opts:
      type: cifs
      o: username=${SMB_ARCHIVE_USER},password=${SMB_ARCHIVE_PASS},uid=1000,gid=1000
      device: //${SMB_ARCHIVE_HOST}/archive
