[[stack]]
name = "resilio-sync"
tags = ["backups"]
[stack.config]
server = "hyperion"
links = [
  "https://resilio-sync.jekotia.net",
  "https://github.com/linuxserver/docker-resilio-sync",
  "https://github.com/linuxserver/docker-resilio-sync/pkgs/container/resilio-sync"
]
git_account = "jekotia"
repo = "jekotia/saturn"
branch = "master"
webhook_enabled = false
run_directory = "docker/stacks/resilio-sync/"
file_paths = [
  "compose.yaml",
  "../../networks/proxy_private.yaml"
]
environment = """
TIMEZONE=[[TIMEZONE]]

# RESILIO_SYNC_URL_PREFIX=
NETWORK_DOMAIN=[[NETWORK_DOMAIN]]

SMB_ARCHIVE_HOST=[[RESILIO_SYNC_SMB_HOST]]
SMB_ARCHIVE_USER=[[RESILIO_SYNC_SMB_USER]]
SMB_ARCHIVE_PASS=[[RESILIO_SYNC_SMB_PASS]]
"""