include:
  - ../../networks/proxy_private.yaml

services:
  emulator-source-backups:
    image: gitea/gitea:1.24.0@sha256:724d420b64da6582b9ac8298856e4791e8a46307f31265cb2630ed0b058073ab
    container_name: emulator-source-backups
    restart: unless-stopped
    environment:
      USER_UID: ${UID:-1000}
      USER_GID: ${GID:-1000}
      GITEA__repository__DEFAULT_BRANCH: master
      GITEA__repository__DEFAULT_MIRROR_REPO_UNITS: repo.code,repo.wiki,repo.projects
      GITEA__repository__DISABLE_HTTP_GIT: true
      GITEA__repository__DISABLE_DOWNLOAD_SOURCE_ARCHIVES: true
      GITEA__server__DISABLE_SSH: true
    #    ports:
    #      - "222:22"
    networks:
      - proxy_private
    volumes:
      - esb.data.data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    labels:
      diun.enable: "true"
      traefik.enable: "true"
      # Frontend => Router
      traefik.http.routers.esb.entrypoints: websecure
      traefik.http.routers.esb.rule: Host(`${ESB_URL_PREFIX:-esb.}${NETWORK_DOMAIN}`)
      traefik.http.routers.esb.tls.certresolver: dns-cloudflare
      # Frontend => Services
      traefik.http.routers.esb.service: esb
      traefik.http.services.esb.loadbalancer.server.port: 3000
volumes:
  esb.data.data:
    driver: local
    driver_opts:
      type: nfs
      o: addr=10.0.0.10,nolock,soft,rw
      device: :/mnt/storage/application_data/emulator-source-backups/app/data
